/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/debug_context';
import * as import1 from '../../../../src/app/components/episodes';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view';
import * as import4 from '@angular/core/src/linker/element';
import * as import5 from '@angular/core/src/linker/view_utils';
import * as import6 from '@angular/core/src/di/injector';
import * as import7 from '@angular/core/src/linker/view_type';
import * as import8 from '@angular/core/src/change_detection/change_detection';
import * as import9 from '@angular/router/src/router_state';
import * as import10 from '../../../../src/app/providers/tvMaze';
import * as import11 from '@angular/core/src/metadata/view';
import * as import12 from '@angular/core/src/linker/component_factory';
import * as import13 from '../../../../src/app/components/sortableHeader';
import * as import14 from '@angular/core/src/linker/template_ref';
import * as import15 from '@angular/common/src/directives/ng_for';
import * as import16 from '@angular/common/src/pipes/async_pipe';
import * as import17 from '../../../../src/app/pipes/orderBy';
import * as import18 from '@angular/common/src/pipes/date_pipe';
import * as import19 from './sortableHeader.ngfactory';
import * as import20 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import21 from '@angular/core/src/i18n/tokens';
import * as import22 from '@angular/core/src/security';
const nodeDebugInfos_Episodes_Host0:import0.StaticNodeDebugInfo[] = [new import0.StaticNodeDebugInfo([import1.Episodes],import1.Episodes,{})];
var renderType_Episodes_Host:import2.RenderComponentType = (null as any);
class _View_Episodes_Host0 extends import3.DebugAppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import4.AppElement;
  _Episodes_0_4:import1.Episodes;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement) {
    super(_View_Episodes_Host0,renderType_Episodes_Host,import7.ViewType.HOST,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_Episodes_Host0);
  }
  createInternal(rootSelector:string):import4.AppElement {
    this._el_0 = this.selectOrCreateHostElement('episodes',rootSelector,this.debug(0,0,0));
    this._appEl_0 = new import4.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_Episodes0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Episodes_0_4 = new import1.Episodes(this.parentInjector.get(import9.ActivatedRoute),this.parentInjector.get(import10.TVMaze));
    this._appEl_0.initComponent(this._Episodes_0_4,[],compView_0);
    compView_0.create(this._Episodes_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import1.Episodes) && (0 === requestNodeIndex))) { return this._Episodes_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Episodes_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_Episodes_Host0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement):import3.AppView<any> {
  if ((renderType_Episodes_Host === (null as any))) { (renderType_Episodes_Host = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.None,[],{})); }
  return new _View_Episodes_Host0(viewUtils,parentInjector,declarationEl);
}
export const EpisodesNgFactory:import12.ComponentFactory<import1.Episodes> = new import12.ComponentFactory<import1.Episodes>('episodes',viewFactory_Episodes_Host0,import1.Episodes);
const styles_Episodes:any[] = [];
const nodeDebugInfos_Episodes0:import0.StaticNodeDebugInfo[] = [
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([import13.SortableHeader],import13.SortableHeader,{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([import13.SortableHeader],import13.SortableHeader,{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([import13.SortableHeader],import13.SortableHeader,{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([
    import14.TemplateRef,
    import15.NgFor
  ]
  ,(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{})
]
;
var renderType_Episodes:import2.RenderComponentType = (null as any);
class _View_Episodes0 extends import3.DebugAppView<import1.Episodes> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _el_10:any;
  /*private*/ _appEl_10:import4.AppElement;
  _SortableHeader_10_4:import13.SortableHeader;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  /*private*/ _appEl_13:import4.AppElement;
  _SortableHeader_13_4:import13.SortableHeader;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  /*private*/ _appEl_16:import4.AppElement;
  _SortableHeader_16_4:import13.SortableHeader;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _text_21:any;
  _el_22:any;
  _text_23:any;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _text_27:any;
  _text_28:any;
  _text_29:any;
  _el_30:any;
  _text_31:any;
  _anchor_32:any;
  /*private*/ _appEl_32:import4.AppElement;
  _TemplateRef_32_5:any;
  _NgFor_32_6:import15.NgFor;
  _text_33:any;
  _text_34:any;
  _text_35:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  _pipe_async_0:import16.AsyncPipe;
  _pipe_orderBy_1:import17.OrderBy;
  _pipe_orderBy_1_0:any;
  /*private*/ _expr_6:any;
  _pipe_date_2:import18.DatePipe;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement) {
    super(_View_Episodes0,renderType_Episodes,import7.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_Episodes0);
  }
  createInternal(rootSelector:string):import4.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n    ',this.debug(0,0,0));
    this._el_1 = this.renderer.createElement(parentRenderNode,'h1',this.debug(1,1,4));
    this._text_2 = this.renderer.createText(this._el_1,'View episodes',this.debug(2,1,8));
    this._text_3 = this.renderer.createText(parentRenderNode,'\n    ',this.debug(3,1,26));
    this._el_4 = this.renderer.createElement(parentRenderNode,'table',this.debug(4,2,4));
    this.renderer.setElementAttribute(this._el_4,'class','table');
    this._text_5 = this.renderer.createText(this._el_4,'\n      ',this.debug(5,2,25));
    this._el_6 = this.renderer.createElement(this._el_4,'thead',this.debug(6,3,6));
    this._text_7 = this.renderer.createText(this._el_6,'\n        ',this.debug(7,3,13));
    this._el_8 = this.renderer.createElement(this._el_6,'tr',this.debug(8,4,8));
    this._text_9 = this.renderer.createText(this._el_8,'\n          ',this.debug(9,4,12));
    this._el_10 = this.renderer.createElement(this._el_8,'th',this.debug(10,5,10));
    this.renderer.setElementAttribute(this._el_10,'sortableHeader','name');
    this._appEl_10 = new import4.AppElement(10,8,this,this._el_10);
    var compView_10:any = import19.viewFactory_SortableHeader0(this.viewUtils,this.injector(10),this._appEl_10);
    this._SortableHeader_10_4 = new import13.SortableHeader();
    this._appEl_10.initComponent(this._SortableHeader_10_4,[],compView_10);
    this._text_11 = this.renderer.createText((null as any),'Name',this.debug(11,5,50));
    compView_10.create(this._SortableHeader_10_4,[[].concat([this._text_11])],(null as any));
    this._text_12 = this.renderer.createText(this._el_8,'\n          ',this.debug(12,5,59));
    this._el_13 = this.renderer.createElement(this._el_8,'th',this.debug(13,6,10));
    this.renderer.setElementAttribute(this._el_13,'sortableHeader','season');
    this._appEl_13 = new import4.AppElement(13,8,this,this._el_13);
    var compView_13:any = import19.viewFactory_SortableHeader0(this.viewUtils,this.injector(13),this._appEl_13);
    this._SortableHeader_13_4 = new import13.SortableHeader();
    this._appEl_13.initComponent(this._SortableHeader_13_4,[],compView_13);
    this._text_14 = this.renderer.createText((null as any),'Season',this.debug(14,6,52));
    compView_13.create(this._SortableHeader_13_4,[[].concat([this._text_14])],(null as any));
    this._text_15 = this.renderer.createText(this._el_8,'\n          ',this.debug(15,6,63));
    this._el_16 = this.renderer.createElement(this._el_8,'th',this.debug(16,7,10));
    this.renderer.setElementAttribute(this._el_16,'sortableHeader','number');
    this._appEl_16 = new import4.AppElement(16,8,this,this._el_16);
    var compView_16:any = import19.viewFactory_SortableHeader0(this.viewUtils,this.injector(16),this._appEl_16);
    this._SortableHeader_16_4 = new import13.SortableHeader();
    this._appEl_16.initComponent(this._SortableHeader_16_4,[],compView_16);
    this._text_17 = this.renderer.createText((null as any),'Number',this.debug(17,7,52));
    compView_16.create(this._SortableHeader_16_4,[[].concat([this._text_17])],(null as any));
    this._text_18 = this.renderer.createText(this._el_8,'\n          ',this.debug(18,7,63));
    this._el_19 = this.renderer.createElement(this._el_8,'th',this.debug(19,8,10));
    this._text_20 = this.renderer.createText(this._el_19,'Air date',this.debug(20,8,14));
    this._text_21 = this.renderer.createText(this._el_8,'\n          ',this.debug(21,8,27));
    this._el_22 = this.renderer.createElement(this._el_8,'th',this.debug(22,9,10));
    this._text_23 = this.renderer.createText(this._el_22,'Runtime',this.debug(23,9,14));
    this._text_24 = this.renderer.createText(this._el_8,'\n          ',this.debug(24,9,26));
    this._el_25 = this.renderer.createElement(this._el_8,'th',this.debug(25,10,10));
    this._text_26 = this.renderer.createText(this._el_25,'Summary',this.debug(26,10,14));
    this._text_27 = this.renderer.createText(this._el_8,'\n        ',this.debug(27,10,26));
    this._text_28 = this.renderer.createText(this._el_6,'\n      ',this.debug(28,11,13));
    this._text_29 = this.renderer.createText(this._el_4,'\n      ',this.debug(29,12,14));
    this._el_30 = this.renderer.createElement(this._el_4,'tbody',this.debug(30,13,6));
    this._text_31 = this.renderer.createText(this._el_30,'\n        ',this.debug(31,13,13));
    this._anchor_32 = this.renderer.createTemplateAnchor(this._el_30,this.debug(32,14,8));
    this._appEl_32 = new import4.AppElement(32,30,this,this._anchor_32);
    this._TemplateRef_32_5 = new import14.TemplateRef_(this._appEl_32,viewFactory_Episodes1);
    this._NgFor_32_6 = new import15.NgFor(this._appEl_32.vcRef,this._TemplateRef_32_5,this.parentInjector.get(import20.IterableDiffers),this.ref);
    this._text_33 = this.renderer.createText(this._el_30,'\n      ',this.debug(33,21,13));
    this._text_34 = this.renderer.createText(this._el_4,'\n    ',this.debug(34,22,14));
    this._text_35 = this.renderer.createText(parentRenderNode,'\n  ',this.debug(35,23,12));
    this._expr_0 = import8.UNINITIALIZED;
    this._expr_1 = import8.UNINITIALIZED;
    this._expr_2 = import8.UNINITIALIZED;
    this._expr_3 = import8.UNINITIALIZED;
    this._expr_4 = import8.UNINITIALIZED;
    this._expr_5 = import8.UNINITIALIZED;
    this.debug((null as any),(null as any),(null as any));
    this._pipe_async_0 = new import16.AsyncPipe(this.ref);
    this._pipe_orderBy_1 = new import17.OrderBy();
    this._pipe_orderBy_1_0 = import5.pureProxy3(this._pipe_orderBy_1.transform.bind(this._pipe_orderBy_1));
    this._expr_6 = import8.UNINITIALIZED;
    this._pipe_date_2 = new import18.DatePipe(this.parentInjector.get(import21.LOCALE_ID));
    this.init([],[
      this._text_0,
      this._el_1,
      this._text_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._text_27,
      this._text_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._anchor_32,
      this._text_33,
      this._text_34,
      this._text_35
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import13.SortableHeader) && ((10 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._SortableHeader_10_4; }
    if (((token === import13.SortableHeader) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._SortableHeader_13_4; }
    if (((token === import13.SortableHeader) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 17)))) { return this._SortableHeader_16_4; }
    if (((token === import14.TemplateRef) && (32 === requestNodeIndex))) { return this._TemplateRef_32_5; }
    if (((token === import15.NgFor) && (32 === requestNodeIndex))) { return this._NgFor_32_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import8.SimpleChange} = (null as any);
    const valUnwrapper:any = new import8.ValueUnwrapper();
    this.debug(10,5,14);
    const currVal_0:any = 'name';
    if (import5.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._SortableHeader_10_4.fieldName = currVal_0;
      this._expr_0 = currVal_0;
    }
    this.debug(10,5,36);
    const currVal_1:any = this.context.sort;
    if (import5.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._SortableHeader_10_4.sort = currVal_1;
      this._expr_1 = currVal_1;
    }
    this.debug(13,6,14);
    const currVal_2:any = 'season';
    if (import5.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._SortableHeader_13_4.fieldName = currVal_2;
      this._expr_2 = currVal_2;
    }
    this.debug(13,6,38);
    const currVal_3:any = this.context.sort;
    if (import5.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._SortableHeader_13_4.sort = currVal_3;
      this._expr_3 = currVal_3;
    }
    this.debug(16,7,14);
    const currVal_4:any = 'number';
    if (import5.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._SortableHeader_16_4.fieldName = currVal_4;
      this._expr_4 = currVal_4;
    }
    this.debug(16,7,38);
    const currVal_5:any = this.context.sort;
    if (import5.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._SortableHeader_16_4.sort = currVal_5;
      this._expr_5 = currVal_5;
    }
    this.debug(32,14,8);
    changes = (null as any);
    this.debug(32,14,12);
    valUnwrapper.reset();
    const currVal_6:any = valUnwrapper.unwrap(import5.castByValue(this._pipe_orderBy_1_0,this._pipe_orderBy_1.transform)(valUnwrapper.unwrap(this._pipe_async_0.transform(this.context.episodes)),this.context.sort.field,this.context.sort.desc));
    if ((valUnwrapper.hasWrappedValue || import5.checkBinding(throwOnChange,this._expr_6,currVal_6))) {
      this._NgFor_32_6.ngForOf = currVal_6;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import8.SimpleChange(this._expr_6,currVal_6);
      this._expr_6 = currVal_6;
    }
    if ((changes !== (null as any))) { this._NgFor_32_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_32_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this.debug(32,14,8);
    this._pipe_async_0.ngOnDestroy();
  }
}
export function viewFactory_Episodes0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement):import3.AppView<import1.Episodes> {
  if ((renderType_Episodes === (null as any))) { (renderType_Episodes = viewUtils.createRenderComponentType('/Users/mattlewis/Code/open-source/angular2-tv/src/app/components/episodes.ts class Episodes - inline template',0,import11.ViewEncapsulation.None,styles_Episodes,{})); }
  return new _View_Episodes0(viewUtils,parentInjector,declarationEl);
}
const nodeDebugInfos_Episodes1:import0.StaticNodeDebugInfo[] = [
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{})
]
;
class _View_Episodes1 extends import3.DebugAppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  _pipe_date_2_0:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement) {
    super(_View_Episodes1,renderType_Episodes,import7.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_Episodes1);
  }
  createInternal(rootSelector:string):import4.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'tr',this.debug(0,14,8));
    this._text_1 = this.renderer.createText(this._el_0,'\n          ',this.debug(1,14,84));
    this._el_2 = this.renderer.createElement(this._el_0,'td',this.debug(2,15,10));
    this._text_3 = this.renderer.createText(this._el_2,'',this.debug(3,15,14));
    this._text_4 = this.renderer.createText(this._el_0,'\n          ',this.debug(4,15,37));
    this._el_5 = this.renderer.createElement(this._el_0,'td',this.debug(5,16,10));
    this._text_6 = this.renderer.createText(this._el_5,'',this.debug(6,16,14));
    this._text_7 = this.renderer.createText(this._el_0,'\n          ',this.debug(7,16,39));
    this._el_8 = this.renderer.createElement(this._el_0,'td',this.debug(8,17,10));
    this._text_9 = this.renderer.createText(this._el_8,'',this.debug(9,17,14));
    this._text_10 = this.renderer.createText(this._el_0,'\n          ',this.debug(10,17,39));
    this._el_11 = this.renderer.createElement(this._el_0,'td',this.debug(11,18,10));
    this._text_12 = this.renderer.createText(this._el_11,'',this.debug(12,18,14));
    this._text_13 = this.renderer.createText(this._el_0,'\n          ',this.debug(13,18,59));
    this._el_14 = this.renderer.createElement(this._el_0,'td',this.debug(14,19,10));
    this._text_15 = this.renderer.createText(this._el_14,'',this.debug(15,19,14));
    this._text_16 = this.renderer.createText(this._el_0,'\n          ',this.debug(16,19,40));
    this._el_17 = this.renderer.createElement(this._el_0,'td',this.debug(17,20,10));
    this._text_18 = this.renderer.createText(this._el_0,'\n        ',this.debug(18,20,49));
    this._expr_0 = import8.UNINITIALIZED;
    this._expr_1 = import8.UNINITIALIZED;
    this._expr_2 = import8.UNINITIALIZED;
    this._pipe_date_2_0 = import5.pureProxy2((<_View_Episodes0>this.parent)._pipe_date_2.transform.bind((<_View_Episodes0>this.parent)._pipe_date_2));
    this._expr_3 = import8.UNINITIALIZED;
    this._expr_4 = import8.UNINITIALIZED;
    this._expr_5 = import8.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._el_17,
      this._text_18
    ]
    ,[],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import8.ValueUnwrapper();
    this.detectContentChildrenChanges(throwOnChange);
    this.debug(3,15,14);
    const currVal_0:any = import5.interpolate(1,'',this.context.$implicit.name,'');
    if (import5.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_3,currVal_0);
      this._expr_0 = currVal_0;
    }
    this.debug(6,16,14);
    const currVal_1:any = import5.interpolate(1,'',this.context.$implicit.season,'');
    if (import5.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setText(this._text_6,currVal_1);
      this._expr_1 = currVal_1;
    }
    this.debug(9,17,14);
    const currVal_2:any = import5.interpolate(1,'',this.context.$implicit.number,'');
    if (import5.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_9,currVal_2);
      this._expr_2 = currVal_2;
    }
    this.debug(12,18,14);
    valUnwrapper.reset();
    const currVal_3:any = import5.interpolate(1,'',valUnwrapper.unwrap(import5.castByValue(this._pipe_date_2_0,(<_View_Episodes0>this.parent)._pipe_date_2.transform)(this.context.$implicit.airstamp,'fullDate')),'');
    if ((valUnwrapper.hasWrappedValue || import5.checkBinding(throwOnChange,this._expr_3,currVal_3))) {
      this.renderer.setText(this._text_12,currVal_3);
      this._expr_3 = currVal_3;
    }
    this.debug(15,19,14);
    const currVal_4:any = import5.interpolate(1,'',this.context.$implicit.runtime,'');
    if (import5.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setText(this._text_15,currVal_4);
      this._expr_4 = currVal_4;
    }
    this.debug(17,20,14);
    const currVal_5:any = this.context.$implicit.summary;
    if (import5.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementProperty(this._el_17,'innerHTML',this.viewUtils.sanitizer.sanitize(import22.SecurityContext.HTML,currVal_5));
      this._expr_5 = currVal_5;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_Episodes1(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement):import3.AppView<any> {
  return new _View_Episodes1(viewUtils,parentInjector,declarationEl);
}