/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/debug_context';
import * as import1 from '../../../../src/app/components/navbar';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view';
import * as import4 from '@angular/core/src/linker/element';
import * as import5 from '@angular/core/src/linker/view_utils';
import * as import6 from '@angular/core/src/di/injector';
import * as import7 from '@angular/core/src/linker/view_type';
import * as import8 from '@angular/core/src/change_detection/change_detection';
import * as import9 from '@angular/common/src/location/location';
import * as import10 from '@angular/core/src/metadata/view';
import * as import11 from '@angular/core/src/linker/component_factory';
import * as import12 from '@angular/router/src/directives/router_link';
import * as import13 from '@angular/router/src/router';
import * as import14 from '@angular/router/src/router_state';
import * as import15 from '@angular/common/src/location/location_strategy';
import * as import16 from '@angular/core/src/security';
const nodeDebugInfos_Navbar_Host0:import0.StaticNodeDebugInfo[] = [new import0.StaticNodeDebugInfo([import1.Navbar],import1.Navbar,{})];
var renderType_Navbar_Host:import2.RenderComponentType = (null as any);
class _View_Navbar_Host0 extends import3.DebugAppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import4.AppElement;
  _Navbar_0_4:import1.Navbar;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement) {
    super(_View_Navbar_Host0,renderType_Navbar_Host,import7.ViewType.HOST,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_Navbar_Host0);
  }
  createInternal(rootSelector:string):import4.AppElement {
    this._el_0 = this.selectOrCreateHostElement('navbar',rootSelector,this.debug(0,0,0));
    this._appEl_0 = new import4.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_Navbar0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Navbar_0_4 = new import1.Navbar(this.parentInjector.get(import9.Location));
    this._appEl_0.initComponent(this._Navbar_0_4,[],compView_0);
    compView_0.create(this._Navbar_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import1.Navbar) && (0 === requestNodeIndex))) { return this._Navbar_0_4; }
    return notFoundResult;
  }
}
function viewFactory_Navbar_Host0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement):import3.AppView<any> {
  if ((renderType_Navbar_Host === (null as any))) { (renderType_Navbar_Host = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,[],{})); }
  return new _View_Navbar_Host0(viewUtils,parentInjector,declarationEl);
}
export const NavbarNgFactory:import11.ComponentFactory<import1.Navbar> = new import11.ComponentFactory<import1.Navbar>('navbar',viewFactory_Navbar_Host0,import1.Navbar);
const styles_Navbar:any[] = [];
const nodeDebugInfos_Navbar0:import0.StaticNodeDebugInfo[] = [
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([import12.RouterLinkWithHref],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([import12.RouterLinkWithHref],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([import12.RouterLinkWithHref],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{})
]
;
var renderType_Navbar:import2.RenderComponentType = (null as any);
class _View_Navbar0 extends import3.DebugAppView<import1.Navbar> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _el_12:any;
  _RouterLinkWithHref_12_3:import12.RouterLinkWithHref;
  _text_13:any;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _el_18:any;
  _RouterLinkWithHref_18_3:import12.RouterLinkWithHref;
  _text_19:any;
  _text_20:any;
  _text_21:any;
  _el_22:any;
  _text_23:any;
  _el_24:any;
  _RouterLinkWithHref_24_3:import12.RouterLinkWithHref;
  _text_25:any;
  _text_26:any;
  _text_27:any;
  _text_28:any;
  _text_29:any;
  _text_30:any;
  /*private*/ _expr_0:any;
  _arr_0:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  _arr_1:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  _arr_2:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement) {
    super(_View_Navbar0,renderType_Navbar,import7.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_Navbar0);
  }
  createInternal(rootSelector:string):import4.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n    ',this.debug(0,0,0));
    this._el_1 = this.renderer.createElement(parentRenderNode,'nav',this.debug(1,1,4));
    this.renderer.setElementAttribute(this._el_1,'class','navbar navbar-fixed-top navbar-light bg-faded');
    this._text_2 = this.renderer.createText(this._el_1,'\n      ',this.debug(2,1,63));
    this._el_3 = this.renderer.createElement(this._el_1,'div',this.debug(3,2,6));
    this.renderer.setElementAttribute(this._el_3,'class','container');
    this._text_4 = this.renderer.createText(this._el_3,'\n        ',this.debug(4,2,29));
    this._el_5 = this.renderer.createElement(this._el_3,'h1',this.debug(5,3,8));
    this.renderer.setElementAttribute(this._el_5,'class','navbar-brand');
    this._text_6 = this.renderer.createText(this._el_5,'Angular 2 TV tracker',this.debug(6,3,33));
    this._text_7 = this.renderer.createText(this._el_3,'\n        ',this.debug(7,3,58));
    this._el_8 = this.renderer.createElement(this._el_3,'ul',this.debug(8,4,8));
    this.renderer.setElementAttribute(this._el_8,'class','nav navbar-nav');
    this._text_9 = this.renderer.createText(this._el_8,'\n          ',this.debug(9,4,35));
    this._el_10 = this.renderer.createElement(this._el_8,'li',this.debug(10,5,10));
    this.renderer.setElementAttribute(this._el_10,'class','nav-item');
    this._text_11 = this.renderer.createText(this._el_10,'\n            ',this.debug(11,5,71));
    this._el_12 = this.renderer.createElement(this._el_10,'a',this.debug(12,6,12));
    this.renderer.setElementAttribute(this._el_12,'class','nav-link');
    this._RouterLinkWithHref_12_3 = new import12.RouterLinkWithHref(this.parentInjector.get(import13.Router),this.parentInjector.get(import14.ActivatedRoute),this.parentInjector.get(import15.LocationStrategy));
    this._text_13 = this.renderer.createText(this._el_12,'Subscribed shows',this.debug(13,6,53));
    this._text_14 = this.renderer.createText(this._el_10,'\n          ',this.debug(14,6,73));
    this._text_15 = this.renderer.createText(this._el_8,'\n          ',this.debug(15,7,15));
    this._el_16 = this.renderer.createElement(this._el_8,'li',this.debug(16,8,10));
    this.renderer.setElementAttribute(this._el_16,'class','nav-item');
    this._text_17 = this.renderer.createText(this._el_16,'\n            ',this.debug(17,8,80));
    this._el_18 = this.renderer.createElement(this._el_16,'a',this.debug(18,9,12));
    this.renderer.setElementAttribute(this._el_18,'class','nav-link');
    this._RouterLinkWithHref_18_3 = new import12.RouterLinkWithHref(this.parentInjector.get(import13.Router),this.parentInjector.get(import14.ActivatedRoute),this.parentInjector.get(import15.LocationStrategy));
    this._text_19 = this.renderer.createText(this._el_18,'Schedule',this.debug(19,9,61));
    this._text_20 = this.renderer.createText(this._el_16,'\n          ',this.debug(20,9,73));
    this._text_21 = this.renderer.createText(this._el_8,'\n          ',this.debug(21,10,15));
    this._el_22 = this.renderer.createElement(this._el_8,'li',this.debug(22,11,10));
    this.renderer.setElementAttribute(this._el_22,'class','nav-item');
    this._text_23 = this.renderer.createText(this._el_22,'\n            ',this.debug(23,11,75));
    this._el_24 = this.renderer.createElement(this._el_22,'a',this.debug(24,12,12));
    this.renderer.setElementAttribute(this._el_24,'class','nav-link');
    this._RouterLinkWithHref_24_3 = new import12.RouterLinkWithHref(this.parentInjector.get(import13.Router),this.parentInjector.get(import14.ActivatedRoute),this.parentInjector.get(import15.LocationStrategy));
    this._text_25 = this.renderer.createText(this._el_24,'Add shows',this.debug(25,12,56));
    this._text_26 = this.renderer.createText(this._el_22,'\n          ',this.debug(26,12,69));
    this._text_27 = this.renderer.createText(this._el_8,'\n        ',this.debug(27,13,15));
    this._text_28 = this.renderer.createText(this._el_3,'\n      ',this.debug(28,14,13));
    this._text_29 = this.renderer.createText(this._el_1,'\n    ',this.debug(29,15,12));
    this._text_30 = this.renderer.createText(parentRenderNode,'\n  ',this.debug(30,16,10));
    this._expr_0 = import8.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_12,'click',this.eventHandler(this._handle_click_12_0.bind(this)));
    this._arr_0 = import5.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._expr_2 = import8.UNINITIALIZED;
    this._expr_3 = import8.UNINITIALIZED;
    this._expr_4 = import8.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_18,'click',this.eventHandler(this._handle_click_18_0.bind(this)));
    this._arr_1 = import5.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._expr_6 = import8.UNINITIALIZED;
    this._expr_7 = import8.UNINITIALIZED;
    this._expr_8 = import8.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_24,'click',this.eventHandler(this._handle_click_24_0.bind(this)));
    this._arr_2 = import5.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._expr_10 = import8.UNINITIALIZED;
    this._expr_11 = import8.UNINITIALIZED;
    this.init([],[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._text_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._text_26,
      this._text_27,
      this._text_28,
      this._text_29,
      this._text_30
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    ,[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import12.RouterLinkWithHref) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._RouterLinkWithHref_12_3; }
    if (((token === import12.RouterLinkWithHref) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 19)))) { return this._RouterLinkWithHref_18_3; }
    if (((token === import12.RouterLinkWithHref) && ((24 <= requestNodeIndex) && (requestNodeIndex <= 25)))) { return this._RouterLinkWithHref_24_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import8.SimpleChange} = (null as any);
    this.debug(12,6,12);
    changes = (null as any);
    this.debug(12,6,32);
    const currVal_2:any = this._arr_0('/');
    if (import5.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._RouterLinkWithHref_12_3.routerLink = currVal_2;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import8.SimpleChange(this._expr_2,currVal_2);
      this._expr_2 = currVal_2;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_12_3.ngOnChanges(changes); }
    this.debug(18,9,12);
    changes = (null as any);
    this.debug(18,9,32);
    const currVal_6:any = this._arr_1('/schedule');
    if (import5.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this._RouterLinkWithHref_18_3.routerLink = currVal_6;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import8.SimpleChange(this._expr_6,currVal_6);
      this._expr_6 = currVal_6;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_18_3.ngOnChanges(changes); }
    this.debug(24,12,12);
    changes = (null as any);
    this.debug(24,12,32);
    const currVal_10:any = this._arr_2('/add');
    if (import5.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this._RouterLinkWithHref_24_3.routerLink = currVal_10;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import8.SimpleChange(this._expr_10,currVal_10);
      this._expr_10 = currVal_10;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_24_3.ngOnChanges(changes); }
    this.detectContentChildrenChanges(throwOnChange);
    this.debug(10,5,31);
    const currVal_0:any = (this.context.location.path() === '');
    if (import5.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementClass(this._el_10,'active',currVal_0);
      this._expr_0 = currVal_0;
    }
    this.debug(12,6,12);
    const currVal_3:any = this._RouterLinkWithHref_12_3.href;
    if (import5.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementProperty(this._el_12,'href',this.viewUtils.sanitizer.sanitize(import16.SecurityContext.URL,currVal_3));
      this._expr_3 = currVal_3;
    }
    this.debug(16,8,31);
    const currVal_4:any = (this.context.location.path() === '/schedule');
    if (import5.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_16,'active',currVal_4);
      this._expr_4 = currVal_4;
    }
    this.debug(18,9,12);
    const currVal_7:any = this._RouterLinkWithHref_18_3.href;
    if (import5.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementProperty(this._el_18,'href',this.viewUtils.sanitizer.sanitize(import16.SecurityContext.URL,currVal_7));
      this._expr_7 = currVal_7;
    }
    this.debug(22,11,31);
    const currVal_8:any = (this.context.location.path() === '/add');
    if (import5.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_22,'active',currVal_8);
      this._expr_8 = currVal_8;
    }
    this.debug(24,12,12);
    const currVal_11:any = this._RouterLinkWithHref_24_3.href;
    if (import5.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementProperty(this._el_24,'href',this.viewUtils.sanitizer.sanitize(import16.SecurityContext.URL,currVal_11));
      this._expr_11 = currVal_11;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this.debug(12,6,12);
    this._RouterLinkWithHref_12_3.ngOnDestroy();
    this.debug(18,9,12);
    this._RouterLinkWithHref_18_3.ngOnDestroy();
    this.debug(24,12,12);
    this._RouterLinkWithHref_24_3.ngOnDestroy();
  }
  private _handle_click_12_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(12,6,12);
    const pd_0:any = ((<any>this._RouterLinkWithHref_12_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
  private _handle_click_18_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(18,9,12);
    const pd_0:any = ((<any>this._RouterLinkWithHref_18_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
  private _handle_click_24_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(24,12,12);
    const pd_0:any = ((<any>this._RouterLinkWithHref_24_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_Navbar0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement):import3.AppView<import1.Navbar> {
  if ((renderType_Navbar === (null as any))) { (renderType_Navbar = viewUtils.createRenderComponentType('/Users/mattlewis/Code/open-source/angular2-tv/src/app/components/navbar.ts class Navbar - inline template',0,import10.ViewEncapsulation.None,styles_Navbar,{})); }
  return new _View_Navbar0(viewUtils,parentInjector,declarationEl);
}