/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/debug_context';
import * as import1 from '../../../../src/app/components/scheduleCalendar';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view';
import * as import4 from '@angular/core/src/linker/element';
import * as import5 from '@angular/core/src/linker/view_utils';
import * as import6 from '@angular/core/src/di/injector';
import * as import7 from '@angular/core/src/linker/view_type';
import * as import8 from '@angular/core/src/change_detection/change_detection';
import * as import9 from '../../../../src/app/providers/localStorage';
import * as import10 from '../../../../src/app/providers/tvMaze';
import * as import11 from '@angular/core/src/metadata/view';
import * as import12 from '@angular/core/src/linker/component_factory';
import * as import13 from '@angular/core/src/linker/template_ref';
import * as import14 from '@angular/common/src/directives/ng_if';
import * as import15 from 'angular2-calendar/dist/esm/src/pipes/calendarDate.pipe';
import * as import16 from 'angular2-calendar/dist/esm/src/providers/calendarDateFormatter.provider';
import * as import17 from '@angular/core/src/i18n/tokens';
import * as import18 from '@angular/common/src/directives/ng_switch';
import * as import19 from 'angular2-calendar/dist/esm/src/components/month/calendarMonthView.component';
import * as import20 from '../../../node_modules/angular2-calendar/dist/esm/src/components/month/calendarMonthView.component.ngfactory';
import * as import21 from 'angular2-calendar/dist/esm/src/components/week/calendarWeekView.component';
import * as import22 from '../../../node_modules/angular2-calendar/dist/esm/src/components/week/calendarWeekView.component.ngfactory';
import * as import23 from 'angular2-calendar/dist/esm/src/components/day/calendarDayView.component';
import * as import24 from '../../../node_modules/angular2-calendar/dist/esm/src/components/day/calendarDayView.component.ngfactory';
const nodeDebugInfos_ScheduleCalendar_Host0:import0.StaticNodeDebugInfo[] = [new import0.StaticNodeDebugInfo([import1.ScheduleCalendar],import1.ScheduleCalendar,{})];
var renderType_ScheduleCalendar_Host:import2.RenderComponentType = (null as any);
class _View_ScheduleCalendar_Host0 extends import3.DebugAppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import4.AppElement;
  _ScheduleCalendar_0_4:import1.ScheduleCalendar;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement) {
    super(_View_ScheduleCalendar_Host0,renderType_ScheduleCalendar_Host,import7.ViewType.HOST,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_ScheduleCalendar_Host0);
  }
  createInternal(rootSelector:string):import4.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ng-component',rootSelector,this.debug(0,0,0));
    this._appEl_0 = new import4.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_ScheduleCalendar0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ScheduleCalendar_0_4 = new import1.ScheduleCalendar(this.parentInjector.get(import9.LocalStorage),this.parentInjector.get(import10.TVMaze));
    this._appEl_0.initComponent(this._ScheduleCalendar_0_4,[],compView_0);
    compView_0.create(this._ScheduleCalendar_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import1.ScheduleCalendar) && (0 === requestNodeIndex))) { return this._ScheduleCalendar_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._ScheduleCalendar_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ScheduleCalendar_Host0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement):import3.AppView<any> {
  if ((renderType_ScheduleCalendar_Host === (null as any))) { (renderType_ScheduleCalendar_Host = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.None,[],{})); }
  return new _View_ScheduleCalendar_Host0(viewUtils,parentInjector,declarationEl);
}
export const ScheduleCalendarNgFactory:import12.ComponentFactory<import1.ScheduleCalendar> = new import12.ComponentFactory<import1.ScheduleCalendar>('ng-component',viewFactory_ScheduleCalendar_Host0,import1.ScheduleCalendar);
const styles_ScheduleCalendar:any[] = [];
const nodeDebugInfos_ScheduleCalendar0:import0.StaticNodeDebugInfo[] = [
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([
    import13.TemplateRef,
    import14.NgIf
  ]
  ,(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([
    import13.TemplateRef,
    import14.NgIf
  ]
  ,(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{})
]
;
var renderType_ScheduleCalendar:import2.RenderComponentType = (null as any);
class _View_ScheduleCalendar0 extends import3.DebugAppView<import1.ScheduleCalendar> {
  _text_0:any;
  _anchor_1:any;
  /*private*/ _appEl_1:import4.AppElement;
  _TemplateRef_1_5:any;
  _NgIf_1_6:import14.NgIf;
  _text_2:any;
  _anchor_3:any;
  /*private*/ _appEl_3:import4.AppElement;
  _TemplateRef_3_5:any;
  _NgIf_3_6:import14.NgIf;
  _text_4:any;
  _el_5:any;
  _el_6:any;
  _text_7:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  _pipe_calendarDate_0:import15.CalendarDate;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement) {
    super(_View_ScheduleCalendar0,renderType_ScheduleCalendar,import7.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_ScheduleCalendar0);
  }
  createInternal(rootSelector:string):import4.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n    ',this.debug(0,0,0));
    this._anchor_1 = this.renderer.createTemplateAnchor(parentRenderNode,this.debug(1,1,4));
    this._appEl_1 = new import4.AppElement(1,(null as any),this,this._anchor_1);
    this._TemplateRef_1_5 = new import13.TemplateRef_(this._appEl_1,viewFactory_ScheduleCalendar1);
    this._NgIf_1_6 = new import14.NgIf(this._appEl_1.vcRef,this._TemplateRef_1_5);
    this._text_2 = this.renderer.createText(parentRenderNode,'\n    ',this.debug(2,3,10));
    this._anchor_3 = this.renderer.createTemplateAnchor(parentRenderNode,this.debug(3,4,4));
    this._appEl_3 = new import4.AppElement(3,(null as any),this,this._anchor_3);
    this._TemplateRef_3_5 = new import13.TemplateRef_(this._appEl_3,viewFactory_ScheduleCalendar2);
    this._NgIf_3_6 = new import14.NgIf(this._appEl_3.vcRef,this._TemplateRef_3_5);
    this._text_4 = this.renderer.createText(parentRenderNode,'\n    ',this.debug(4,53,10));
    this._el_5 = this.renderer.createElement(parentRenderNode,'br',this.debug(5,54,4));
    this._el_6 = this.renderer.createElement(parentRenderNode,'br',this.debug(6,54,8));
    this._text_7 = this.renderer.createText(parentRenderNode,'\n  ',this.debug(7,54,12));
    this._expr_0 = import8.UNINITIALIZED;
    this._expr_1 = import8.UNINITIALIZED;
    this.debug((null as any),(null as any),(null as any));
    this._pipe_calendarDate_0 = new import15.CalendarDate(this.parentInjector.get(import16.CalendarDateFormatter),this.parentInjector.get(import17.LOCALE_ID));
    this.init([],[
      this._text_0,
      this._anchor_1,
      this._text_2,
      this._anchor_3,
      this._text_4,
      this._el_5,
      this._el_6,
      this._text_7
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import13.TemplateRef) && (1 === requestNodeIndex))) { return this._TemplateRef_1_5; }
    if (((token === import14.NgIf) && (1 === requestNodeIndex))) { return this._NgIf_1_6; }
    if (((token === import13.TemplateRef) && (3 === requestNodeIndex))) { return this._TemplateRef_3_5; }
    if (((token === import14.NgIf) && (3 === requestNodeIndex))) { return this._NgIf_3_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.debug(1,1,32);
    const currVal_0:boolean = !this.context.showsLoaded;
    if (import5.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgIf_1_6.ngIf = currVal_0;
      this._expr_0 = currVal_0;
    }
    this.debug(3,4,9);
    const currVal_1:any = this.context.showsLoaded;
    if (import5.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._NgIf_3_6.ngIf = currVal_1;
      this._expr_1 = currVal_1;
    }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
export function viewFactory_ScheduleCalendar0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement):import3.AppView<import1.ScheduleCalendar> {
  if ((renderType_ScheduleCalendar === (null as any))) { (renderType_ScheduleCalendar = viewUtils.createRenderComponentType('/Users/mattlewis/Code/open-source/angular2-tv/src/app/components/scheduleCalendar.ts class ScheduleCalendar - inline template',0,import11.ViewEncapsulation.None,styles_ScheduleCalendar,{})); }
  return new _View_ScheduleCalendar0(viewUtils,parentInjector,declarationEl);
}
const nodeDebugInfos_ScheduleCalendar1:import0.StaticNodeDebugInfo[] = [
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{})
]
;
class _View_ScheduleCalendar1 extends import3.DebugAppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement) {
    super(_View_ScheduleCalendar1,renderType_ScheduleCalendar,import7.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_ScheduleCalendar1);
  }
  createInternal(rootSelector:string):import4.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',this.debug(0,1,4));
    this.renderer.setElementAttribute(this._el_0,'class','text-xs-center');
    this._text_1 = this.renderer.createText(this._el_0,'\n      ',this.debug(1,1,53));
    this._el_2 = this.renderer.createElement(this._el_0,'h1',this.debug(2,2,6));
    this._text_3 = this.renderer.createText(this._el_2,'Loading...',this.debug(3,2,10));
    this._text_4 = this.renderer.createText(this._el_0,'\n    ',this.debug(4,2,25));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4
    ]
    ,[],[]);
    return (null as any);
  }
}
function viewFactory_ScheduleCalendar1(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement):import3.AppView<any> {
  return new _View_ScheduleCalendar1(viewUtils,parentInjector,declarationEl);
}
const nodeDebugInfos_ScheduleCalendar2:import0.StaticNodeDebugInfo[] = [
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([import18.NgSwitch],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([
    import13.TemplateRef,
    import18.NgSwitchCase
  ]
  ,(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([
    import13.TemplateRef,
    import18.NgSwitchCase
  ]
  ,(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([
    import13.TemplateRef,
    import18.NgSwitchCase
  ]
  ,(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{})
]
;
class _View_ScheduleCalendar2 extends import3.DebugAppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _text_16:any;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _text_23:any;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _el_27:any;
  _text_28:any;
  _el_29:any;
  _text_30:any;
  _text_31:any;
  _el_32:any;
  _text_33:any;
  _text_34:any;
  _el_35:any;
  _text_36:any;
  _text_37:any;
  _text_38:any;
  _text_39:any;
  _text_40:any;
  _el_41:any;
  _text_42:any;
  _el_43:any;
  _NgSwitch_43_3:import18.NgSwitch;
  _text_44:any;
  _anchor_45:any;
  /*private*/ _appEl_45:import4.AppElement;
  _TemplateRef_45_5:any;
  _NgSwitchCase_45_6:import18.NgSwitchCase;
  _text_46:any;
  _anchor_47:any;
  /*private*/ _appEl_47:import4.AppElement;
  _TemplateRef_47_5:any;
  _NgSwitchCase_47_6:import18.NgSwitchCase;
  _text_48:any;
  _anchor_49:any;
  /*private*/ _appEl_49:import4.AppElement;
  _TemplateRef_49_5:any;
  _NgSwitchCase_49_6:import18.NgSwitchCase;
  _text_50:any;
  _text_51:any;
  _pipe_calendarDate_0_0:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement) {
    super(_View_ScheduleCalendar2,renderType_ScheduleCalendar,import7.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_ScheduleCalendar2);
  }
  createInternal(rootSelector:string):import4.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',this.debug(0,4,4));
    this._text_1 = this.renderer.createText(this._el_0,'\n      ',this.debug(1,4,29));
    this._el_2 = this.renderer.createElement(this._el_0,'div',this.debug(2,5,6));
    this.renderer.setElementAttribute(this._el_2,'class','row');
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',this.debug(3,5,23));
    this._el_4 = this.renderer.createElement(this._el_2,'div',this.debug(4,6,8));
    this.renderer.setElementAttribute(this._el_4,'class','col-md-4');
    this._text_5 = this.renderer.createText(this._el_4,'\n          ',this.debug(5,6,30));
    this._el_6 = this.renderer.createElement(this._el_4,'div',this.debug(6,7,10));
    this.renderer.setElementAttribute(this._el_6,'class','btn-group');
    this._text_7 = this.renderer.createText(this._el_6,'\n            ',this.debug(7,7,33));
    this._el_8 = this.renderer.createElement(this._el_6,'div',this.debug(8,8,12));
    this.renderer.setElementAttribute(this._el_8,'class','btn btn-primary');
    this._text_9 = this.renderer.createText(this._el_8,'\n              Previous\n            ',this.debug(9,8,63));
    this._text_10 = this.renderer.createText(this._el_6,'\n            ',this.debug(10,10,18));
    this._el_11 = this.renderer.createElement(this._el_6,'div',this.debug(11,11,12));
    this.renderer.setElementAttribute(this._el_11,'class','btn btn-secondary');
    this._text_12 = this.renderer.createText(this._el_11,'\n              Today\n            ',this.debug(12,11,61));
    this._text_13 = this.renderer.createText(this._el_6,'\n            ',this.debug(13,13,18));
    this._el_14 = this.renderer.createElement(this._el_6,'div',this.debug(14,14,12));
    this.renderer.setElementAttribute(this._el_14,'class','btn btn-primary');
    this._text_15 = this.renderer.createText(this._el_14,'\n              Next\n            ',this.debug(15,14,63));
    this._text_16 = this.renderer.createText(this._el_6,'\n          ',this.debug(16,16,18));
    this._text_17 = this.renderer.createText(this._el_4,'\n        ',this.debug(17,17,16));
    this._text_18 = this.renderer.createText(this._el_2,'\n        ',this.debug(18,18,14));
    this._el_19 = this.renderer.createElement(this._el_2,'div',this.debug(19,19,8));
    this.renderer.setElementAttribute(this._el_19,'class','col-md-4 text-xs-center');
    this._text_20 = this.renderer.createText(this._el_19,'\n          ',this.debug(20,19,45));
    this._el_21 = this.renderer.createElement(this._el_19,'h3',this.debug(21,20,10));
    this._text_22 = this.renderer.createText(this._el_21,'',this.debug(22,20,14));
    this._text_23 = this.renderer.createText(this._el_19,'\n        ',this.debug(23,20,74));
    this._text_24 = this.renderer.createText(this._el_2,'\n        ',this.debug(24,21,14));
    this._el_25 = this.renderer.createElement(this._el_2,'div',this.debug(25,22,8));
    this.renderer.setElementAttribute(this._el_25,'class','col-md-4 text-xs-right');
    this._text_26 = this.renderer.createText(this._el_25,'\n          ',this.debug(26,22,44));
    this._el_27 = this.renderer.createElement(this._el_25,'div',this.debug(27,23,10));
    this.renderer.setElementAttribute(this._el_27,'class','btn-group');
    this._text_28 = this.renderer.createText(this._el_27,'\n            ',this.debug(28,23,33));
    this._el_29 = this.renderer.createElement(this._el_27,'div',this.debug(29,24,12));
    this.renderer.setElementAttribute(this._el_29,'class','btn btn-primary');
    this._text_30 = this.renderer.createText(this._el_29,'Month',this.debug(30,24,100));
    this._text_31 = this.renderer.createText(this._el_27,'\n            ',this.debug(31,24,111));
    this._el_32 = this.renderer.createElement(this._el_27,'div',this.debug(32,25,12));
    this.renderer.setElementAttribute(this._el_32,'class','btn btn-primary');
    this._text_33 = this.renderer.createText(this._el_32,'Week',this.debug(33,25,98));
    this._text_34 = this.renderer.createText(this._el_27,'\n            ',this.debug(34,25,108));
    this._el_35 = this.renderer.createElement(this._el_27,'div',this.debug(35,26,12));
    this.renderer.setElementAttribute(this._el_35,'class','btn btn-primary');
    this._text_36 = this.renderer.createText(this._el_35,'Day',this.debug(36,26,96));
    this._text_37 = this.renderer.createText(this._el_27,'\n          ',this.debug(37,26,105));
    this._text_38 = this.renderer.createText(this._el_25,'\n        ',this.debug(38,27,16));
    this._text_39 = this.renderer.createText(this._el_2,'\n      ',this.debug(39,28,14));
    this._text_40 = this.renderer.createText(this._el_0,'\n      ',this.debug(40,29,12));
    this._el_41 = this.renderer.createElement(this._el_0,'br',this.debug(41,30,6));
    this._text_42 = this.renderer.createText(this._el_0,'\n      ',this.debug(42,30,10));
    this._el_43 = this.renderer.createElement(this._el_0,'div',this.debug(43,31,6));
    this._NgSwitch_43_3 = new import18.NgSwitch();
    this._text_44 = this.renderer.createText(this._el_43,'\n        ',this.debug(44,31,29));
    this._anchor_45 = this.renderer.createTemplateAnchor(this._el_43,this.debug(45,32,8));
    this._appEl_45 = new import4.AppElement(45,43,this,this._anchor_45);
    this._TemplateRef_45_5 = new import13.TemplateRef_(this._appEl_45,viewFactory_ScheduleCalendar3);
    this._NgSwitchCase_45_6 = new import18.NgSwitchCase(this._appEl_45.vcRef,this._TemplateRef_45_5,this._NgSwitch_43_3);
    this._text_46 = this.renderer.createText(this._el_43,'\n        ',this.debug(46,39,34));
    this._anchor_47 = this.renderer.createTemplateAnchor(this._el_43,this.debug(47,40,8));
    this._appEl_47 = new import4.AppElement(47,43,this,this._anchor_47);
    this._TemplateRef_47_5 = new import13.TemplateRef_(this._appEl_47,viewFactory_ScheduleCalendar4);
    this._NgSwitchCase_47_6 = new import18.NgSwitchCase(this._appEl_47.vcRef,this._TemplateRef_47_5,this._NgSwitch_43_3);
    this._text_48 = this.renderer.createText(this._el_43,'\n        ',this.debug(48,45,33));
    this._anchor_49 = this.renderer.createTemplateAnchor(this._el_43,this.debug(49,46,8));
    this._appEl_49 = new import4.AppElement(49,43,this,this._anchor_49);
    this._TemplateRef_49_5 = new import13.TemplateRef_(this._appEl_49,viewFactory_ScheduleCalendar5);
    this._NgSwitchCase_49_6 = new import18.NgSwitchCase(this._appEl_49.vcRef,this._TemplateRef_49_5,this._NgSwitch_43_3);
    this._text_50 = this.renderer.createText(this._el_43,'\n      ',this.debug(50,51,32));
    this._text_51 = this.renderer.createText(this._el_0,'\n    ',this.debug(51,52,12));
    var disposable_0:Function = this.renderer.listen(this._el_8,'click',this.eventHandler(this._handle_click_8_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_11,'click',this.eventHandler(this._handle_click_11_0.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_14,'click',this.eventHandler(this._handle_click_14_0.bind(this)));
    this._pipe_calendarDate_0_0 = import5.pureProxy3((<_View_ScheduleCalendar0>this.parent)._pipe_calendarDate_0.transform.bind((<_View_ScheduleCalendar0>this.parent)._pipe_calendarDate_0));
    this._expr_3 = import8.UNINITIALIZED;
    this._expr_5 = import8.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_29,'click',this.eventHandler(this._handle_click_29_0.bind(this)));
    this._expr_7 = import8.UNINITIALIZED;
    var disposable_4:Function = this.renderer.listen(this._el_32,'click',this.eventHandler(this._handle_click_32_0.bind(this)));
    this._expr_9 = import8.UNINITIALIZED;
    var disposable_5:Function = this.renderer.listen(this._el_35,'click',this.eventHandler(this._handle_click_35_0.bind(this)));
    this._expr_10 = import8.UNINITIALIZED;
    this._expr_11 = import8.UNINITIALIZED;
    this._expr_12 = import8.UNINITIALIZED;
    this._expr_13 = import8.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._text_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._text_37,
      this._text_38,
      this._text_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._el_43,
      this._text_44,
      this._anchor_45,
      this._text_46,
      this._anchor_47,
      this._text_48,
      this._anchor_49,
      this._text_50,
      this._text_51
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5
    ]
    ,[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import13.TemplateRef) && (45 === requestNodeIndex))) { return this._TemplateRef_45_5; }
    if (((token === import18.NgSwitchCase) && (45 === requestNodeIndex))) { return this._NgSwitchCase_45_6; }
    if (((token === import13.TemplateRef) && (47 === requestNodeIndex))) { return this._TemplateRef_47_5; }
    if (((token === import18.NgSwitchCase) && (47 === requestNodeIndex))) { return this._NgSwitchCase_47_6; }
    if (((token === import13.TemplateRef) && (49 === requestNodeIndex))) { return this._TemplateRef_49_5; }
    if (((token === import18.NgSwitchCase) && (49 === requestNodeIndex))) { return this._NgSwitchCase_49_6; }
    if (((token === import18.NgSwitch) && ((43 <= requestNodeIndex) && (requestNodeIndex <= 50)))) { return this._NgSwitch_43_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import8.ValueUnwrapper();
    this.debug(43,31,11);
    const currVal_10:any = this.parent.context.view;
    if (import5.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this._NgSwitch_43_3.ngSwitch = currVal_10;
      this._expr_10 = currVal_10;
    }
    this.debug(45,33,10);
    const currVal_11:any = 'month';
    if (import5.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this._NgSwitchCase_45_6.ngSwitchCase = currVal_11;
      this._expr_11 = currVal_11;
    }
    this.debug(47,41,10);
    const currVal_12:any = 'week';
    if (import5.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this._NgSwitchCase_47_6.ngSwitchCase = currVal_12;
      this._expr_12 = currVal_12;
    }
    this.debug(49,47,10);
    const currVal_13:any = 'day';
    if (import5.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this._NgSwitchCase_49_6.ngSwitchCase = currVal_13;
      this._expr_13 = currVal_13;
    }
    this.detectContentChildrenChanges(throwOnChange);
    this.debug(22,20,14);
    valUnwrapper.reset();
    const currVal_3:any = import5.interpolate(1,'',valUnwrapper.unwrap(import5.castByValue(this._pipe_calendarDate_0_0,(<_View_ScheduleCalendar0>this.parent)._pipe_calendarDate_0.transform)(this.parent.context.viewDate,(this.parent.context.view + 'ViewTitle'),'en')),'');
    if ((valUnwrapper.hasWrappedValue || import5.checkBinding(throwOnChange,this._expr_3,currVal_3))) {
      this.renderer.setText(this._text_22,currVal_3);
      this._expr_3 = currVal_3;
    }
    this.debug(29,24,66);
    const currVal_5:any = (this.parent.context.view === 'month');
    if (import5.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_29,'active',currVal_5);
      this._expr_5 = currVal_5;
    }
    this.debug(32,25,65);
    const currVal_7:any = (this.parent.context.view === 'week');
    if (import5.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_32,'active',currVal_7);
      this._expr_7 = currVal_7;
    }
    this.debug(35,26,64);
    const currVal_9:any = (this.parent.context.view === 'day');
    if (import5.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_35,'active',currVal_9);
      this._expr_9 = currVal_9;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_8_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(8,8,41);
    const pd_0:any = ((<any>this.parent.context.decrement()) !== false);
    return (true && pd_0);
  }
  private _handle_click_11_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(11,11,43);
    const pd_0:any = ((<any>this.parent.context.today()) !== false);
    return (true && pd_0);
  }
  private _handle_click_14_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(14,14,41);
    const pd_0:any = ((<any>this.parent.context.increment()) !== false);
    return (true && pd_0);
  }
  private _handle_click_29_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(29,24,41);
    const pd_0:any = ((<any>(this.parent.context.view = 'month')) !== false);
    return (true && pd_0);
  }
  private _handle_click_32_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(32,25,41);
    const pd_0:any = ((<any>(this.parent.context.view = 'week')) !== false);
    return (true && pd_0);
  }
  private _handle_click_35_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(35,26,41);
    const pd_0:any = ((<any>(this.parent.context.view = 'day')) !== false);
    return (true && pd_0);
  }
}
function viewFactory_ScheduleCalendar2(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement):import3.AppView<any> {
  return new _View_ScheduleCalendar2(viewUtils,parentInjector,declarationEl);
}
const nodeDebugInfos_ScheduleCalendar3:import0.StaticNodeDebugInfo[] = [
  new import0.StaticNodeDebugInfo([import19.CalendarMonthViewComponent],import19.CalendarMonthViewComponent,{}),
  new import0.StaticNodeDebugInfo([],(null as any),{})
]
;
class _View_ScheduleCalendar3 extends import3.DebugAppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import4.AppElement;
  _CalendarMonthViewComponent_0_4:import19.CalendarMonthViewComponent;
  _text_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement) {
    super(_View_ScheduleCalendar3,renderType_ScheduleCalendar,import7.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_ScheduleCalendar3);
  }
  createInternal(rootSelector:string):import4.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'mwl-calendar-month-view',this.debug(0,32,8));
    this._appEl_0 = new import4.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import20.viewFactory_CalendarMonthViewComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._CalendarMonthViewComponent_0_4 = new import19.CalendarMonthViewComponent(compView_0.ref,this.parent.parentInjector.get(import17.LOCALE_ID));
    this._appEl_0.initComponent(this._CalendarMonthViewComponent_0_4,[],compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n        ',this.debug(1,38,53));
    compView_0.create(this._CalendarMonthViewComponent_0_4,[],(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'dayClicked',this.eventHandler(this._handle_dayClicked_0_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_0,'eventClicked',this.eventHandler(this._handle_eventClicked_0_1.bind(this)));
    this._expr_2 = import8.UNINITIALIZED;
    this._expr_3 = import8.UNINITIALIZED;
    this._expr_4 = import8.UNINITIALIZED;
    const subscription_0:any = this._CalendarMonthViewComponent_0_4.dayClicked.subscribe(this.eventHandler(this._handle_dayClicked_0_0.bind(this)));
    const subscription_1:any = this._CalendarMonthViewComponent_0_4.eventClicked.subscribe(this.eventHandler(this._handle_eventClicked_0_1.bind(this)));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[
      disposable_0,
      disposable_1
    ]
    ,[
      subscription_0,
      subscription_1
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import19.CalendarMonthViewComponent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._CalendarMonthViewComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changed:boolean = true;
    var changes:{[key: string]:import8.SimpleChange} = (null as any);
    this.debug(0,32,8);
    changes = (null as any);
    changed = false;
    this.debug(0,34,10);
    const currVal_2:any = this.parent.parent.context.viewDate;
    if (import5.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._CalendarMonthViewComponent_0_4.viewDate = currVal_2;
      if ((changes === (null as any))) { (changes = {}); }
      changes['viewDate'] = new import8.SimpleChange(this._expr_2,currVal_2);
      changed = true;
      this._expr_2 = currVal_2;
    }
    this.debug(0,35,10);
    const currVal_3:any = this.parent.parent.context.events;
    if (import5.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._CalendarMonthViewComponent_0_4.events = currVal_3;
      if ((changes === (null as any))) { (changes = {}); }
      changes['events'] = new import8.SimpleChange(this._expr_3,currVal_3);
      changed = true;
      this._expr_3 = currVal_3;
    }
    this.debug(0,36,10);
    const currVal_4:any = this.parent.parent.context.activeDayIsOpen;
    if (import5.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._CalendarMonthViewComponent_0_4.activeDayIsOpen = currVal_4;
      if ((changes === (null as any))) { (changes = {}); }
      changes['activeDayIsOpen'] = new import8.SimpleChange(this._expr_4,currVal_4);
      changed = true;
      this._expr_4 = currVal_4;
    }
    if (changed) { this._appEl_0.componentView.markAsCheckOnce(); }
    if ((changes !== (null as any))) { this._CalendarMonthViewComponent_0_4.ngOnChanges(changes); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._CalendarMonthViewComponent_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this.debug(0,32,8);
    this._CalendarMonthViewComponent_0_4.ngOnDestroy();
  }
  private _handle_dayClicked_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(0,37,10);
    const pd_0:any = ((<any>this.parent.parent.context.dayClicked($event.day)) !== false);
    return (true && pd_0);
  }
  private _handle_eventClicked_0_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(0,38,10);
    const pd_0:any = ((<any>this.parent.parent.context.openEpisode($event.event)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_ScheduleCalendar3(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement):import3.AppView<any> {
  return new _View_ScheduleCalendar3(viewUtils,parentInjector,declarationEl);
}
const nodeDebugInfos_ScheduleCalendar4:import0.StaticNodeDebugInfo[] = [
  new import0.StaticNodeDebugInfo([import21.CalendarWeekViewComponent],import21.CalendarWeekViewComponent,{}),
  new import0.StaticNodeDebugInfo([],(null as any),{})
]
;
class _View_ScheduleCalendar4 extends import3.DebugAppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import4.AppElement;
  _CalendarWeekViewComponent_0_4:import21.CalendarWeekViewComponent;
  _text_1:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement) {
    super(_View_ScheduleCalendar4,renderType_ScheduleCalendar,import7.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_ScheduleCalendar4);
  }
  createInternal(rootSelector:string):import4.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'mwl-calendar-week-view',this.debug(0,40,8));
    this._appEl_0 = new import4.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import22.viewFactory_CalendarWeekViewComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._CalendarWeekViewComponent_0_4 = new import21.CalendarWeekViewComponent(compView_0.ref,this.parent.parentInjector.get(import17.LOCALE_ID));
    this._appEl_0.initComponent(this._CalendarWeekViewComponent_0_4,[],compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n        ',this.debug(1,44,53));
    compView_0.create(this._CalendarWeekViewComponent_0_4,[],(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'eventClicked',this.eventHandler(this._handle_eventClicked_0_0.bind(this)));
    this._expr_1 = import8.UNINITIALIZED;
    this._expr_2 = import8.UNINITIALIZED;
    const subscription_0:any = this._CalendarWeekViewComponent_0_4.eventClicked.subscribe(this.eventHandler(this._handle_eventClicked_0_0.bind(this)));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[disposable_0],[subscription_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import21.CalendarWeekViewComponent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._CalendarWeekViewComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changed:boolean = true;
    var changes:{[key: string]:import8.SimpleChange} = (null as any);
    this.debug(0,40,8);
    changes = (null as any);
    changed = false;
    this.debug(0,42,10);
    const currVal_1:any = this.parent.parent.context.viewDate;
    if (import5.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._CalendarWeekViewComponent_0_4.viewDate = currVal_1;
      if ((changes === (null as any))) { (changes = {}); }
      changes['viewDate'] = new import8.SimpleChange(this._expr_1,currVal_1);
      changed = true;
      this._expr_1 = currVal_1;
    }
    this.debug(0,43,10);
    const currVal_2:any = this.parent.parent.context.events;
    if (import5.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._CalendarWeekViewComponent_0_4.events = currVal_2;
      if ((changes === (null as any))) { (changes = {}); }
      changes['events'] = new import8.SimpleChange(this._expr_2,currVal_2);
      changed = true;
      this._expr_2 = currVal_2;
    }
    if (changed) { this._appEl_0.componentView.markAsCheckOnce(); }
    if ((changes !== (null as any))) { this._CalendarWeekViewComponent_0_4.ngOnChanges(changes); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._CalendarWeekViewComponent_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this.debug(0,40,8);
    this._CalendarWeekViewComponent_0_4.ngOnDestroy();
  }
  private _handle_eventClicked_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(0,44,10);
    const pd_0:any = ((<any>this.parent.parent.context.openEpisode($event.event)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_ScheduleCalendar4(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement):import3.AppView<any> {
  return new _View_ScheduleCalendar4(viewUtils,parentInjector,declarationEl);
}
const nodeDebugInfos_ScheduleCalendar5:import0.StaticNodeDebugInfo[] = [
  new import0.StaticNodeDebugInfo([import23.CalendarDayViewComponent],import23.CalendarDayViewComponent,{}),
  new import0.StaticNodeDebugInfo([],(null as any),{})
]
;
class _View_ScheduleCalendar5 extends import3.DebugAppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import4.AppElement;
  _CalendarDayViewComponent_0_4:import23.CalendarDayViewComponent;
  _text_1:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement) {
    super(_View_ScheduleCalendar5,renderType_ScheduleCalendar,import7.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_ScheduleCalendar5);
  }
  createInternal(rootSelector:string):import4.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'mwl-calendar-day-view',this.debug(0,46,8));
    this._appEl_0 = new import4.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import24.viewFactory_CalendarDayViewComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._CalendarDayViewComponent_0_4 = new import23.CalendarDayViewComponent(compView_0.ref,this.parent.parentInjector.get(import17.LOCALE_ID));
    this._appEl_0.initComponent(this._CalendarDayViewComponent_0_4,[],compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n        ',this.debug(1,50,53));
    compView_0.create(this._CalendarDayViewComponent_0_4,[],(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'eventClicked',this.eventHandler(this._handle_eventClicked_0_0.bind(this)));
    this._expr_1 = import8.UNINITIALIZED;
    this._expr_2 = import8.UNINITIALIZED;
    const subscription_0:any = this._CalendarDayViewComponent_0_4.eventClicked.subscribe(this.eventHandler(this._handle_eventClicked_0_0.bind(this)));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[disposable_0],[subscription_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import23.CalendarDayViewComponent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._CalendarDayViewComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changed:boolean = true;
    var changes:{[key: string]:import8.SimpleChange} = (null as any);
    this.debug(0,46,8);
    changes = (null as any);
    changed = false;
    this.debug(0,48,10);
    const currVal_1:any = this.parent.parent.context.viewDate;
    if (import5.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._CalendarDayViewComponent_0_4.viewDate = currVal_1;
      if ((changes === (null as any))) { (changes = {}); }
      changes['viewDate'] = new import8.SimpleChange(this._expr_1,currVal_1);
      changed = true;
      this._expr_1 = currVal_1;
    }
    this.debug(0,49,10);
    const currVal_2:any = this.parent.parent.context.events;
    if (import5.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._CalendarDayViewComponent_0_4.events = currVal_2;
      if ((changes === (null as any))) { (changes = {}); }
      changes['events'] = new import8.SimpleChange(this._expr_2,currVal_2);
      changed = true;
      this._expr_2 = currVal_2;
    }
    if (changed) { this._appEl_0.componentView.markAsCheckOnce(); }
    if ((changes !== (null as any))) { this._CalendarDayViewComponent_0_4.ngOnChanges(changes); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._CalendarDayViewComponent_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this.debug(0,46,8);
    this._CalendarDayViewComponent_0_4.ngOnDestroy();
  }
  private _handle_eventClicked_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(0,50,10);
    const pd_0:any = ((<any>this.parent.parent.context.openEpisode($event.event)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_ScheduleCalendar5(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement):import3.AppView<any> {
  return new _View_ScheduleCalendar5(viewUtils,parentInjector,declarationEl);
}