/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/debug_context';
import * as import1 from '../../../../src/app/components/searchShows';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view';
import * as import4 from '@angular/core/src/linker/element';
import * as import5 from '@angular/core/src/linker/view_utils';
import * as import6 from '@angular/core/src/di/injector';
import * as import7 from '@angular/core/src/linker/view_type';
import * as import8 from '@angular/core/src/change_detection/change_detection';
import * as import9 from '../../../../src/app/providers/tvMaze';
import * as import10 from '@angular/core/src/metadata/view';
import * as import11 from '@angular/core/src/linker/component_factory';
import * as import12 from '../../../../src/app/components/searchBox';
import * as import13 from '../../../../src/app/components/showList';
import * as import14 from 'angular2-bootstrap-confirm/dist/esm/src/confirmOptions.provider';
import * as import15 from 'angular2-bootstrap-confirm/dist/esm/src/position.provider';
import * as import16 from '@ng-bootstrap/ng-bootstrap/util/positioning';
import * as import17 from './searchBox.ngfactory';
import * as import18 from '@angular/forms/src/form_builder';
import * as import19 from './showList.ngfactory';
import * as import20 from '../../../../src/app/providers/localStorage';
const nodeDebugInfos_SearchShows_Host0:import0.StaticNodeDebugInfo[] = [new import0.StaticNodeDebugInfo([import1.SearchShows],import1.SearchShows,{})];
var renderType_SearchShows_Host:import2.RenderComponentType = (null as any);
class _View_SearchShows_Host0 extends import3.DebugAppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import4.AppElement;
  _SearchShows_0_4:import1.SearchShows;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement) {
    super(_View_SearchShows_Host0,renderType_SearchShows_Host,import7.ViewType.HOST,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_SearchShows_Host0);
  }
  createInternal(rootSelector:string):import4.AppElement {
    this._el_0 = this.selectOrCreateHostElement('search-shows',rootSelector,this.debug(0,0,0));
    this._appEl_0 = new import4.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_SearchShows0(this.viewUtils,this.injector(0),this._appEl_0);
    this._SearchShows_0_4 = new import1.SearchShows(this.parentInjector.get(import9.TVMaze));
    this._appEl_0.initComponent(this._SearchShows_0_4,[],compView_0);
    compView_0.create(this._SearchShows_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import1.SearchShows) && (0 === requestNodeIndex))) { return this._SearchShows_0_4; }
    return notFoundResult;
  }
}
function viewFactory_SearchShows_Host0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement):import3.AppView<any> {
  if ((renderType_SearchShows_Host === (null as any))) { (renderType_SearchShows_Host = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,[],{})); }
  return new _View_SearchShows_Host0(viewUtils,parentInjector,declarationEl);
}
export const SearchShowsNgFactory:import11.ComponentFactory<import1.SearchShows> = new import11.ComponentFactory<import1.SearchShows>('search-shows',viewFactory_SearchShows_Host0,import1.SearchShows);
const styles_SearchShows:any[] = [];
const nodeDebugInfos_SearchShows0:import0.StaticNodeDebugInfo[] = [
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([import12.SearchBox],import12.SearchBox,{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([
    import13.ShowList,
    import14.ConfirmOptions,
    import15.Position
  ]
  ,import13.ShowList,{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{})
]
;
var renderType_SearchShows:import2.RenderComponentType = (null as any);
class _View_SearchShows0 extends import3.DebugAppView<import1.SearchShows> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _text_5:any;
  _el_6:any;
  /*private*/ _appEl_6:import4.AppElement;
  _SearchBox_6_4:import12.SearchBox;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _el_11:any;
  /*private*/ _appEl_11:import4.AppElement;
  _ShowList_11_4:import13.ShowList;
  __ConfirmOptions_11_5:any;
  __Position_11_6:import16.Positioning;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _text_15:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement) {
    super(_View_SearchShows0,renderType_SearchShows,import7.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_SearchShows0);
  }
  get _ConfirmOptions_11_5():any {
    this.debug(11,6,4);
    if ((this.__ConfirmOptions_11_5 == (null as any))) { (this.__ConfirmOptions_11_5 = import13.confirmOptionsFactory()); }
    return this.__ConfirmOptions_11_5;
  }
  get _Position_11_6():import16.Positioning {
    this.debug(11,6,4);
    if ((this.__Position_11_6 == (null as any))) { (this.__Position_11_6 = new import16.Positioning()); }
    return this.__Position_11_6;
  }
  createInternal(rootSelector:string):import4.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n    ',this.debug(0,0,0));
    this._el_1 = this.renderer.createElement(parentRenderNode,'div',this.debug(1,1,4));
    this.renderer.setElementAttribute(this._el_1,'class','row');
    this._text_2 = this.renderer.createText(this._el_1,'\n      ',this.debug(2,1,21));
    this._el_3 = this.renderer.createElement(this._el_1,'h1',this.debug(3,2,6));
    this.renderer.setElementAttribute(this._el_3,'class','col-md-6');
    this._text_4 = this.renderer.createText(this._el_3,'Add a show',this.debug(4,2,27));
    this._text_5 = this.renderer.createText(this._el_1,'\n      ',this.debug(5,2,42));
    this._el_6 = this.renderer.createElement(this._el_1,'search-box',this.debug(6,3,6));
    this.renderer.setElementAttribute(this._el_6,'class','col-md-6');
    this._appEl_6 = new import4.AppElement(6,1,this,this._el_6);
    var compView_6:any = import17.viewFactory_SearchBox0(this.viewUtils,this.injector(6),this._appEl_6);
    this._SearchBox_6_4 = new import12.SearchBox(this.parentInjector.get(import18.FormBuilder));
    this._appEl_6.initComponent(this._SearchBox_6_4,[],compView_6);
    compView_6.create(this._SearchBox_6_4,[],(null as any));
    this._text_7 = this.renderer.createText(this._el_1,'\n    ',this.debug(7,3,82));
    this._text_8 = this.renderer.createText(parentRenderNode,'\n    ',this.debug(8,4,10));
    this._el_9 = this.renderer.createElement(parentRenderNode,'br',this.debug(9,5,4));
    this._text_10 = this.renderer.createText(parentRenderNode,'\n    ',this.debug(10,5,8));
    this._el_11 = this.renderer.createElement(parentRenderNode,'show-list',this.debug(11,6,4));
    this._appEl_11 = new import4.AppElement(11,(null as any),this,this._el_11);
    var compView_11:any = import19.viewFactory_ShowList0(this.viewUtils,this.injector(11),this._appEl_11);
    this._ShowList_11_4 = new import13.ShowList(this.parentInjector.get(import20.LocalStorage),this.parentInjector.get(import9.TVMaze));
    this._appEl_11.initComponent(this._ShowList_11_4,[],compView_11);
    compView_11.create(this._ShowList_11_4,[],(null as any));
    this._text_12 = this.renderer.createText(parentRenderNode,'\n    ',this.debug(12,6,43));
    this._el_13 = this.renderer.createElement(parentRenderNode,'div',this.debug(13,7,4));
    this.renderer.setElementAttribute(this._el_13,'class','alert alert-danger');
    this._text_14 = this.renderer.createText(this._el_13,'\n      No TV shows found with this name\n    ',this.debug(14,9,56));
    this._text_15 = this.renderer.createText(parentRenderNode,'\n  ',this.debug(15,11,10));
    var disposable_0:Function = this.renderer.listen(this._el_6,'runSearch',this.eventHandler(this._handle_runSearch_6_0.bind(this)));
    const subscription_0:any = this._SearchBox_6_4.runSearch.subscribe(this.eventHandler(this._handle_runSearch_6_0.bind(this)));
    this._expr_1 = import8.UNINITIALIZED;
    this._expr_2 = import8.UNINITIALIZED;
    this.init([],[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._text_15
    ]
    ,[disposable_0],[subscription_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import12.SearchBox) && (6 === requestNodeIndex))) { return this._SearchBox_6_4; }
    if (((token === import13.ShowList) && (11 === requestNodeIndex))) { return this._ShowList_11_4; }
    if (((token === import14.ConfirmOptions) && (11 === requestNodeIndex))) { return this._ConfirmOptions_11_5; }
    if (((token === import15.Position) && (11 === requestNodeIndex))) { return this._Position_11_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import8.SimpleChange} = (null as any);
    this.debug(11,6,4);
    changes = (null as any);
    this.debug(11,6,15);
    const currVal_1:any = this.context.shows;
    if (import5.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._ShowList_11_4.shows = currVal_1;
      if ((changes === (null as any))) { (changes = {}); }
      changes['shows'] = new import8.SimpleChange(this._expr_1,currVal_1);
      this._expr_1 = currVal_1;
    }
    if ((changes !== (null as any))) { this._ShowList_11_4.ngOnChanges(changes); }
    this.detectContentChildrenChanges(throwOnChange);
    this.debug(13,9,6);
    const currVal_2:boolean = (!this.context.error && (!this.context.shows || (this.context.shows.length > 0)));
    if (import5.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementProperty(this._el_13,'hidden',currVal_2);
      this._expr_2 = currVal_2;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_runSearch_6_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(6,3,35);
    const pd_0:any = ((<any>this.context.searchShows($event)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_SearchShows0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement):import3.AppView<import1.SearchShows> {
  if ((renderType_SearchShows === (null as any))) { (renderType_SearchShows = viewUtils.createRenderComponentType('/Users/mattlewis/Code/open-source/angular2-tv/src/app/components/searchShows.ts class SearchShows - inline template',0,import10.ViewEncapsulation.None,styles_SearchShows,{})); }
  return new _View_SearchShows0(viewUtils,parentInjector,declarationEl);
}