/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/debug_context';
import * as import1 from '../../../../src/app/components/searchBox';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view';
import * as import4 from '@angular/core/src/linker/element';
import * as import5 from '@angular/core/src/linker/view_utils';
import * as import6 from '@angular/core/src/di/injector';
import * as import7 from '@angular/core/src/linker/view_type';
import * as import8 from '@angular/core/src/change_detection/change_detection';
import * as import9 from '@angular/forms/src/form_builder';
import * as import10 from '@angular/core/src/metadata/view';
import * as import11 from '@angular/core/src/linker/component_factory';
import * as import12 from '@angular/forms/src/directives/reactive_directives/form_group_directive';
import * as import13 from '@angular/forms/src/directives/control_container';
import * as import14 from '@angular/forms/src/directives/ng_control_status';
import * as import15 from '@angular/forms/src/directives/default_value_accessor';
import * as import16 from '@angular/forms/src/directives/control_value_accessor';
import * as import17 from '@angular/forms/src/directives/reactive_directives/form_control_name';
import * as import18 from '@angular/forms/src/directives/ng_control';
import * as import19 from '@angular/core/src/linker/element_ref';
const nodeDebugInfos_SearchBox_Host0:import0.StaticNodeDebugInfo[] = [new import0.StaticNodeDebugInfo([import1.SearchBox],import1.SearchBox,{})];
var renderType_SearchBox_Host:import2.RenderComponentType = (null as any);
class _View_SearchBox_Host0 extends import3.DebugAppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import4.AppElement;
  _SearchBox_0_4:import1.SearchBox;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement) {
    super(_View_SearchBox_Host0,renderType_SearchBox_Host,import7.ViewType.HOST,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_SearchBox_Host0);
  }
  createInternal(rootSelector:string):import4.AppElement {
    this._el_0 = this.selectOrCreateHostElement('search-box',rootSelector,this.debug(0,0,0));
    this._appEl_0 = new import4.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_SearchBox0(this.viewUtils,this.injector(0),this._appEl_0);
    this._SearchBox_0_4 = new import1.SearchBox(this.parentInjector.get(import9.FormBuilder));
    this._appEl_0.initComponent(this._SearchBox_0_4,[],compView_0);
    compView_0.create(this._SearchBox_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import1.SearchBox) && (0 === requestNodeIndex))) { return this._SearchBox_0_4; }
    return notFoundResult;
  }
}
function viewFactory_SearchBox_Host0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement):import3.AppView<any> {
  if ((renderType_SearchBox_Host === (null as any))) { (renderType_SearchBox_Host = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,[],{})); }
  return new _View_SearchBox_Host0(viewUtils,parentInjector,declarationEl);
}
export const SearchBoxNgFactory:import11.ComponentFactory<import1.SearchBox> = new import11.ComponentFactory<import1.SearchBox>('search-box',viewFactory_SearchBox_Host0,import1.SearchBox);
const styles_SearchBox:any[] = [];
const nodeDebugInfos_SearchBox0:import0.StaticNodeDebugInfo[] = [
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([
    import12.FormGroupDirective,
    import13.ControlContainer,
    import14.NgControlStatusGroup
  ]
  ,(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([
    import15.DefaultValueAccessor,
    import16.NG_VALUE_ACCESSOR,
    import17.FormControlName,
    import18.NgControl,
    import14.NgControlStatus
  ]
  ,(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{})
]
;
var renderType_SearchBox:import2.RenderComponentType = (null as any);
class _View_SearchBox0 extends import3.DebugAppView<import1.SearchBox> {
  _text_0:any;
  _el_1:any;
  _FormGroupDirective_1_3:import12.FormGroupDirective;
  _ControlContainer_1_4:any;
  _NgControlStatusGroup_1_5:import14.NgControlStatusGroup;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _el_5:any;
  _DefaultValueAccessor_5_3:import15.DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_5_4:any[];
  _FormControlName_5_5:import17.FormControlName;
  _NgControl_5_6:any;
  _NgControlStatus_5_7:import14.NgControlStatus;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  _text_14:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement) {
    super(_View_SearchBox0,renderType_SearchBox,import7.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_SearchBox0);
  }
  createInternal(rootSelector:string):import4.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n    ',this.debug(0,0,0));
    this._el_1 = this.renderer.createElement(parentRenderNode,'form',this.debug(1,1,4));
    this._FormGroupDirective_1_3 = new import12.FormGroupDirective((null as any),(null as any));
    this._ControlContainer_1_4 = this._FormGroupDirective_1_3;
    this._NgControlStatusGroup_1_5 = new import14.NgControlStatusGroup(this._ControlContainer_1_4);
    this._text_2 = this.renderer.createText(this._el_1,'\n      ',this.debug(2,1,110));
    this._el_3 = this.renderer.createElement(this._el_1,'div',this.debug(3,2,6));
    this.renderer.setElementAttribute(this._el_3,'class','input-group');
    this._text_4 = this.renderer.createText(this._el_3,'\n        ',this.debug(4,2,31));
    this._el_5 = this.renderer.createElement(this._el_3,'input',this.debug(5,3,8));
    this.renderer.setElementAttribute(this._el_5,'class','form-control');
    this.renderer.setElementAttribute(this._el_5,'formControlName','query');
    this.renderer.setElementAttribute(this._el_5,'type','search');
    this._DefaultValueAccessor_5_3 = new import15.DefaultValueAccessor(this.renderer,new import19.ElementRef(this._el_5));
    this._NG_VALUE_ACCESSOR_5_4 = [this._DefaultValueAccessor_5_3];
    this._FormControlName_5_5 = new import17.FormControlName(this._ControlContainer_1_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_5_4);
    this._NgControl_5_6 = this._FormControlName_5_5;
    this._NgControlStatus_5_7 = new import14.NgControlStatus(this._NgControl_5_6);
    this._text_6 = this.renderer.createText(this._el_3,'\n        ',this.debug(6,3,74));
    this._el_7 = this.renderer.createElement(this._el_3,'span',this.debug(7,4,8));
    this.renderer.setElementAttribute(this._el_7,'class','input-group-btn');
    this._text_8 = this.renderer.createText(this._el_7,'\n          ',this.debug(8,4,38));
    this._el_9 = this.renderer.createElement(this._el_7,'button',this.debug(9,5,10));
    this.renderer.setElementAttribute(this._el_9,'class','btn btn-primary');
    this.renderer.setElementAttribute(this._el_9,'type','submit');
    this._text_10 = this.renderer.createText(this._el_9,'\n            Search\n           ',this.debug(10,8,43));
    this._text_11 = this.renderer.createText(this._el_7,'\n        ',this.debug(11,10,20));
    this._text_12 = this.renderer.createText(this._el_3,'\n      ',this.debug(12,11,15));
    this._text_13 = this.renderer.createText(this._el_1,'\n    ',this.debug(13,12,12));
    this._text_14 = this.renderer.createText(parentRenderNode,'\n  ',this.debug(14,13,11));
    var disposable_0:Function = this.renderer.listen(this._el_1,'submit',this.eventHandler(this._handle_submit_1_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_1,'reset',this.eventHandler(this._handle_reset_1_1.bind(this)));
    this._expr_3 = import8.UNINITIALIZED;
    this._expr_4 = import8.UNINITIALIZED;
    this._expr_5 = import8.UNINITIALIZED;
    this._expr_6 = import8.UNINITIALIZED;
    this._expr_7 = import8.UNINITIALIZED;
    this._expr_8 = import8.UNINITIALIZED;
    this._expr_9 = import8.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_5,'input',this.eventHandler(this._handle_input_5_0.bind(this)));
    var disposable_3:Function = this.renderer.listen(this._el_5,'blur',this.eventHandler(this._handle_blur_5_1.bind(this)));
    this._expr_12 = import8.UNINITIALIZED;
    this._expr_13 = import8.UNINITIALIZED;
    this._expr_14 = import8.UNINITIALIZED;
    this._expr_15 = import8.UNINITIALIZED;
    this._expr_16 = import8.UNINITIALIZED;
    this._expr_17 = import8.UNINITIALIZED;
    this._expr_18 = import8.UNINITIALIZED;
    this._expr_19 = import8.UNINITIALIZED;
    this.init([],[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._text_12,
      this._text_13,
      this._text_14
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3
    ]
    ,[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import15.DefaultValueAccessor) && (5 === requestNodeIndex))) { return this._DefaultValueAccessor_5_3; }
    if (((token === import16.NG_VALUE_ACCESSOR) && (5 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_5_4; }
    if (((token === import17.FormControlName) && (5 === requestNodeIndex))) { return this._FormControlName_5_5; }
    if (((token === import18.NgControl) && (5 === requestNodeIndex))) { return this._NgControl_5_6; }
    if (((token === import14.NgControlStatus) && (5 === requestNodeIndex))) { return this._NgControlStatus_5_7; }
    if (((token === import12.FormGroupDirective) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._FormGroupDirective_1_3; }
    if (((token === import13.ControlContainer) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._ControlContainer_1_4; }
    if (((token === import14.NgControlStatusGroup) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._NgControlStatusGroup_1_5; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import8.SimpleChange} = (null as any);
    this.debug(1,1,4);
    changes = (null as any);
    this.debug(1,1,85);
    const currVal_3:any = this.context.searchForm;
    if (import5.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._FormGroupDirective_1_3.form = currVal_3;
      if ((changes === (null as any))) { (changes = {}); }
      changes['form'] = new import8.SimpleChange(this._expr_3,currVal_3);
      this._expr_3 = currVal_3;
    }
    if ((changes !== (null as any))) { this._FormGroupDirective_1_3.ngOnChanges(changes); }
    this.debug(5,3,8);
    changes = (null as any);
    this.debug(5,3,50);
    const currVal_12:any = 'query';
    if (import5.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this._FormControlName_5_5.name = currVal_12;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import8.SimpleChange(this._expr_12,currVal_12);
      this._expr_12 = currVal_12;
    }
    if ((changes !== (null as any))) { this._FormControlName_5_5.ngOnChanges(changes); }
    this.detectContentChildrenChanges(throwOnChange);
    this.debug(1,1,4);
    const currVal_4:any = this._NgControlStatusGroup_1_5.ngClassUntouched;
    if (import5.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_1,'ng-untouched',currVal_4);
      this._expr_4 = currVal_4;
    }
    this.debug(1,1,4);
    const currVal_5:any = this._NgControlStatusGroup_1_5.ngClassTouched;
    if (import5.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_1,'ng-touched',currVal_5);
      this._expr_5 = currVal_5;
    }
    this.debug(1,1,4);
    const currVal_6:any = this._NgControlStatusGroup_1_5.ngClassPristine;
    if (import5.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_1,'ng-pristine',currVal_6);
      this._expr_6 = currVal_6;
    }
    this.debug(1,1,4);
    const currVal_7:any = this._NgControlStatusGroup_1_5.ngClassDirty;
    if (import5.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_1,'ng-dirty',currVal_7);
      this._expr_7 = currVal_7;
    }
    this.debug(1,1,4);
    const currVal_8:any = this._NgControlStatusGroup_1_5.ngClassValid;
    if (import5.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_1,'ng-valid',currVal_8);
      this._expr_8 = currVal_8;
    }
    this.debug(1,1,4);
    const currVal_9:any = this._NgControlStatusGroup_1_5.ngClassInvalid;
    if (import5.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_1,'ng-invalid',currVal_9);
      this._expr_9 = currVal_9;
    }
    this.debug(5,3,8);
    const currVal_13:any = this._NgControlStatus_5_7.ngClassUntouched;
    if (import5.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setElementClass(this._el_5,'ng-untouched',currVal_13);
      this._expr_13 = currVal_13;
    }
    this.debug(5,3,8);
    const currVal_14:any = this._NgControlStatus_5_7.ngClassTouched;
    if (import5.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setElementClass(this._el_5,'ng-touched',currVal_14);
      this._expr_14 = currVal_14;
    }
    this.debug(5,3,8);
    const currVal_15:any = this._NgControlStatus_5_7.ngClassPristine;
    if (import5.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setElementClass(this._el_5,'ng-pristine',currVal_15);
      this._expr_15 = currVal_15;
    }
    this.debug(5,3,8);
    const currVal_16:any = this._NgControlStatus_5_7.ngClassDirty;
    if (import5.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this.renderer.setElementClass(this._el_5,'ng-dirty',currVal_16);
      this._expr_16 = currVal_16;
    }
    this.debug(5,3,8);
    const currVal_17:any = this._NgControlStatus_5_7.ngClassValid;
    if (import5.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setElementClass(this._el_5,'ng-valid',currVal_17);
      this._expr_17 = currVal_17;
    }
    this.debug(5,3,8);
    const currVal_18:any = this._NgControlStatus_5_7.ngClassInvalid;
    if (import5.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementClass(this._el_5,'ng-invalid',currVal_18);
      this._expr_18 = currVal_18;
    }
    this.debug(9,8,12);
    const currVal_19:boolean = !this.context.searchForm.valid;
    if (import5.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this.renderer.setElementProperty(this._el_9,'disabled',currVal_19);
      this._expr_19 = currVal_19;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this.debug(5,3,8);
    this._FormControlName_5_5.ngOnDestroy();
  }
  private _handle_submit_1_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(1,1,10);
    $event.preventDefault();
    const pd_0:any = ((<any>this.context.runSearch.emit(this.context.searchForm.value.query)) !== false);
    this.debug(1,1,4);
    const pd_1:any = ((<any>this._FormGroupDirective_1_3.onSubmit()) !== false);
    return ((true && pd_0) && pd_1);
  }
  private _handle_reset_1_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(1,1,4);
    const pd_0:any = ((<any>this._FormGroupDirective_1_3.onReset()) !== false);
    return (true && pd_0);
  }
  private _handle_input_5_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(5,3,8);
    const pd_0:any = ((<any>this._DefaultValueAccessor_5_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_5_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(5,3,8);
    const pd_0:any = ((<any>this._DefaultValueAccessor_5_3.onTouched()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_SearchBox0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement):import3.AppView<import1.SearchBox> {
  if ((renderType_SearchBox === (null as any))) { (renderType_SearchBox = viewUtils.createRenderComponentType('/Users/mattlewis/Code/open-source/angular2-tv/src/app/components/searchBox.ts class SearchBox - inline template',0,import10.ViewEncapsulation.None,styles_SearchBox,{})); }
  return new _View_SearchBox0(viewUtils,parentInjector,declarationEl);
}