/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/debug_context';
import * as import1 from '../../../../src/app/components/showList';
import * as import2 from 'angular2-bootstrap-confirm/dist/esm/src/confirmOptions.provider';
import * as import3 from 'angular2-bootstrap-confirm/dist/esm/src/position.provider';
import * as import4 from '@angular/core/src/render/api';
import * as import5 from '@angular/core/src/linker/view';
import * as import6 from '@angular/core/src/linker/element';
import * as import7 from '@ng-bootstrap/ng-bootstrap/util/positioning';
import * as import8 from '@angular/core/src/linker/view_utils';
import * as import9 from '@angular/core/src/di/injector';
import * as import10 from '@angular/core/src/linker/view_type';
import * as import11 from '@angular/core/src/change_detection/change_detection';
import * as import12 from '../../../../src/app/providers/localStorage';
import * as import13 from '../../../../src/app/providers/tvMaze';
import * as import14 from '@angular/core/src/metadata/view';
import * as import15 from '@angular/core/src/linker/component_factory';
import * as import16 from '../../../../src/app/components/sortableHeader';
import * as import17 from '@angular/core/src/linker/template_ref';
import * as import18 from '@angular/common/src/directives/ng_for';
import * as import19 from '../../../../src/app/pipes/orderBy';
import * as import20 from '@angular/common/src/pipes/date_pipe';
import * as import21 from './sortableHeader.ngfactory';
import * as import22 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import23 from '@angular/core/src/i18n/tokens';
import * as import24 from 'angular2-bootstrap-confirm/dist/esm/src/confirm.directive';
import * as import25 from '@angular/router/src/directives/router_link';
import * as import26 from '@angular/core/src/linker/element_ref';
import * as import27 from '@angular/core/src/linker/component_factory_resolver';
import * as import28 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import29 from '@angular/router/src/router';
import * as import30 from '@angular/router/src/router_state';
import * as import31 from '@angular/common/src/location/location_strategy';
import * as import32 from '@angular/core/src/security';
  const nodeDebugInfos_ShowList_Host0:import0.StaticNodeDebugInfo[] = [new import0.StaticNodeDebugInfo([
    import1.ShowList,
    import2.ConfirmOptions,
    import3.Position
  ]
,import1.ShowList,{})];
var renderType_ShowList_Host:import4.RenderComponentType = (null as any);
class _View_ShowList_Host0 extends import5.DebugAppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import6.AppElement;
  _ShowList_0_4:import1.ShowList;
  __ConfirmOptions_0_5:any;
  __Position_0_6:import7.Positioning;
  constructor(viewUtils:import8.ViewUtils,parentInjector:import9.Injector,declarationEl:import6.AppElement) {
    super(_View_ShowList_Host0,renderType_ShowList_Host,import10.ViewType.HOST,viewUtils,parentInjector,declarationEl,import11.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_ShowList_Host0);
  }
  get _ConfirmOptions_0_5():any {
    this.debug(0,0,0);
    if ((this.__ConfirmOptions_0_5 == (null as any))) { (this.__ConfirmOptions_0_5 = import1.confirmOptionsFactory()); }
    return this.__ConfirmOptions_0_5;
  }
  get _Position_0_6():import7.Positioning {
    this.debug(0,0,0);
    if ((this.__Position_0_6 == (null as any))) { (this.__Position_0_6 = new import7.Positioning()); }
    return this.__Position_0_6;
  }
  createInternal(rootSelector:string):import6.AppElement {
    this._el_0 = this.selectOrCreateHostElement('show-list',rootSelector,this.debug(0,0,0));
    this._appEl_0 = new import6.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_ShowList0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ShowList_0_4 = new import1.ShowList(this.parentInjector.get(import12.LocalStorage),this.parentInjector.get(import13.TVMaze));
    this._appEl_0.initComponent(this._ShowList_0_4,[],compView_0);
    compView_0.create(this._ShowList_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import1.ShowList) && (0 === requestNodeIndex))) { return this._ShowList_0_4; }
    if (((token === import2.ConfirmOptions) && (0 === requestNodeIndex))) { return this._ConfirmOptions_0_5; }
    if (((token === import3.Position) && (0 === requestNodeIndex))) { return this._Position_0_6; }
    return notFoundResult;
  }
}
function viewFactory_ShowList_Host0(viewUtils:import8.ViewUtils,parentInjector:import9.Injector,declarationEl:import6.AppElement):import5.AppView<any> {
  if ((renderType_ShowList_Host === (null as any))) { (renderType_ShowList_Host = viewUtils.createRenderComponentType('',0,import14.ViewEncapsulation.None,[],{})); }
  return new _View_ShowList_Host0(viewUtils,parentInjector,declarationEl);
}
export const ShowListNgFactory:import15.ComponentFactory<import1.ShowList> = new import15.ComponentFactory<import1.ShowList>('show-list',viewFactory_ShowList_Host0,import1.ShowList);
const styles_ShowList:any[] = [];
const nodeDebugInfos_ShowList0:import0.StaticNodeDebugInfo[] = [
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([import16.SortableHeader],import16.SortableHeader,{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([import16.SortableHeader],import16.SortableHeader,{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([import16.SortableHeader],import16.SortableHeader,{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([import16.SortableHeader],import16.SortableHeader,{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([
    import17.TemplateRef,
    import18.NgFor
  ]
  ,(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{})
]
;
var renderType_ShowList:import4.RenderComponentType = (null as any);
class _View_ShowList0 extends import5.DebugAppView<import1.ShowList> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  /*private*/ _appEl_7:import6.AppElement;
  _SortableHeader_7_4:import16.SortableHeader;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  /*private*/ _appEl_13:import6.AppElement;
  _SortableHeader_13_4:import16.SortableHeader;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  /*private*/ _appEl_19:import6.AppElement;
  _SortableHeader_19_4:import16.SortableHeader;
  _text_20:any;
  _text_21:any;
  _el_22:any;
  /*private*/ _appEl_22:import6.AppElement;
  _SortableHeader_22_4:import16.SortableHeader;
  _text_23:any;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _text_27:any;
  _text_28:any;
  _el_29:any;
  _text_30:any;
  _anchor_31:any;
  /*private*/ _appEl_31:import6.AppElement;
  _TemplateRef_31_5:any;
  _NgFor_31_6:import18.NgFor;
  _text_32:any;
  _text_33:any;
  _text_34:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  _pipe_orderBy_0:import19.OrderBy;
  _pipe_orderBy_0_0:any;
  /*private*/ _expr_9:any;
  _pipe_date_1:import20.DatePipe;
  constructor(viewUtils:import8.ViewUtils,parentInjector:import9.Injector,declarationEl:import6.AppElement) {
    super(_View_ShowList0,renderType_ShowList,import10.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import11.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_ShowList0);
  }
  createInternal(rootSelector:string):import6.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n    ',this.debug(0,0,0));
    this._el_1 = this.renderer.createElement(parentRenderNode,'table',this.debug(1,1,4));
    this.renderer.setElementAttribute(this._el_1,'class','table');
    this._text_2 = this.renderer.createText(this._el_1,'\n      ',this.debug(2,1,65));
    this._el_3 = this.renderer.createElement(this._el_1,'thead',this.debug(3,2,6));
    this._text_4 = this.renderer.createText(this._el_3,'\n        ',this.debug(4,2,13));
    this._el_5 = this.renderer.createElement(this._el_3,'tr',this.debug(5,3,8));
    this._text_6 = this.renderer.createText(this._el_5,'\n          ',this.debug(6,3,12));
    this._el_7 = this.renderer.createElement(this._el_5,'th',this.debug(7,4,10));
    this.renderer.setElementAttribute(this._el_7,'sortableHeader','name');
    this._appEl_7 = new import6.AppElement(7,5,this,this._el_7);
    var compView_7:any = import21.viewFactory_SortableHeader0(this.viewUtils,this.injector(7),this._appEl_7);
    this._SortableHeader_7_4 = new import16.SortableHeader();
    this._appEl_7.initComponent(this._SortableHeader_7_4,[],compView_7);
    this._text_8 = this.renderer.createText((null as any),'Name',this.debug(8,4,50));
    compView_7.create(this._SortableHeader_7_4,[[].concat([this._text_8])],(null as any));
    this._text_9 = this.renderer.createText(this._el_5,'\n          ',this.debug(9,4,59));
    this._el_10 = this.renderer.createElement(this._el_5,'th',this.debug(10,5,10));
    this._text_11 = this.renderer.createText(this._el_10,'Image',this.debug(11,5,14));
    this._text_12 = this.renderer.createText(this._el_5,'\n          ',this.debug(12,5,24));
    this._el_13 = this.renderer.createElement(this._el_5,'th',this.debug(13,6,10));
    this.renderer.setElementAttribute(this._el_13,'sortableHeader','network.name');
    this._appEl_13 = new import6.AppElement(13,5,this,this._el_13);
    var compView_13:any = import21.viewFactory_SortableHeader0(this.viewUtils,this.injector(13),this._appEl_13);
    this._SortableHeader_13_4 = new import16.SortableHeader();
    this._appEl_13.initComponent(this._SortableHeader_13_4,[],compView_13);
    this._text_14 = this.renderer.createText((null as any),'Network',this.debug(14,6,58));
    compView_13.create(this._SortableHeader_13_4,[[].concat([this._text_14])],(null as any));
    this._text_15 = this.renderer.createText(this._el_5,'\n          ',this.debug(15,6,70));
    this._el_16 = this.renderer.createElement(this._el_5,'th',this.debug(16,7,10));
    this._text_17 = this.renderer.createText(this._el_16,'Summary',this.debug(17,7,14));
    this._text_18 = this.renderer.createText(this._el_5,'\n          ',this.debug(18,7,26));
    this._el_19 = this.renderer.createElement(this._el_5,'th',this.debug(19,8,10));
    this.renderer.setElementAttribute(this._el_19,'sortableHeader','status');
    this._appEl_19 = new import6.AppElement(19,5,this,this._el_19);
    var compView_19:any = import21.viewFactory_SortableHeader0(this.viewUtils,this.injector(19),this._appEl_19);
    this._SortableHeader_19_4 = new import16.SortableHeader();
    this._appEl_19.initComponent(this._SortableHeader_19_4,[],compView_19);
    this._text_20 = this.renderer.createText((null as any),'Status',this.debug(20,8,52));
    compView_19.create(this._SortableHeader_19_4,[[].concat([this._text_20])],(null as any));
    this._text_21 = this.renderer.createText(this._el_5,'\n          ',this.debug(21,8,63));
    this._el_22 = this.renderer.createElement(this._el_5,'th',this.debug(22,9,10));
    this.renderer.setElementAttribute(this._el_22,'sortableHeader','nextEpisode.airstamp');
    this._appEl_22 = new import6.AppElement(22,5,this,this._el_22);
    var compView_22:any = import21.viewFactory_SortableHeader0(this.viewUtils,this.injector(22),this._appEl_22);
    this._SortableHeader_22_4 = new import16.SortableHeader();
    this._appEl_22.initComponent(this._SortableHeader_22_4,[],compView_22);
    this._text_23 = this.renderer.createText((null as any),'Next episode',this.debug(23,9,66));
    compView_22.create(this._SortableHeader_22_4,[[].concat([this._text_23])],(null as any));
    this._text_24 = this.renderer.createText(this._el_5,'\n          ',this.debug(24,9,83));
    this._el_25 = this.renderer.createElement(this._el_5,'th',this.debug(25,10,10));
    this._text_26 = this.renderer.createText(this._el_5,'\n        ',this.debug(26,10,19));
    this._text_27 = this.renderer.createText(this._el_3,'\n      ',this.debug(27,11,13));
    this._text_28 = this.renderer.createText(this._el_1,'\n      ',this.debug(28,12,14));
    this._el_29 = this.renderer.createElement(this._el_1,'tbody',this.debug(29,13,6));
    this._text_30 = this.renderer.createText(this._el_29,'\n        ',this.debug(30,13,13));
    this._anchor_31 = this.renderer.createTemplateAnchor(this._el_29,this.debug(31,14,8));
    this._appEl_31 = new import6.AppElement(31,29,this,this._anchor_31);
    this._TemplateRef_31_5 = new import17.TemplateRef_(this._appEl_31,viewFactory_ShowList1);
    this._NgFor_31_6 = new import18.NgFor(this._appEl_31.vcRef,this._TemplateRef_31_5,this.parentInjector.get(import22.IterableDiffers),this.ref);
    this._text_32 = this.renderer.createText(this._el_29,'\n      ',this.debug(32,50,13));
    this._text_33 = this.renderer.createText(this._el_1,'\n    ',this.debug(33,51,14));
    this._text_34 = this.renderer.createText(parentRenderNode,'\n  ',this.debug(34,52,12));
    this._expr_0 = import11.UNINITIALIZED;
    this._expr_1 = import11.UNINITIALIZED;
    this._expr_2 = import11.UNINITIALIZED;
    this._expr_3 = import11.UNINITIALIZED;
    this._expr_4 = import11.UNINITIALIZED;
    this._expr_5 = import11.UNINITIALIZED;
    this._expr_6 = import11.UNINITIALIZED;
    this._expr_7 = import11.UNINITIALIZED;
    this._expr_8 = import11.UNINITIALIZED;
    this.debug((null as any),(null as any),(null as any));
    this._pipe_orderBy_0 = new import19.OrderBy();
    this._pipe_orderBy_0_0 = import8.pureProxy3(this._pipe_orderBy_0.transform.bind(this._pipe_orderBy_0));
    this._expr_9 = import11.UNINITIALIZED;
    this._pipe_date_1 = new import20.DatePipe(this.parentInjector.get(import23.LOCALE_ID));
    this.init([],[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._text_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._anchor_31,
      this._text_32,
      this._text_33,
      this._text_34
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import16.SortableHeader) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._SortableHeader_7_4; }
    if (((token === import16.SortableHeader) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._SortableHeader_13_4; }
    if (((token === import16.SortableHeader) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 20)))) { return this._SortableHeader_19_4; }
    if (((token === import16.SortableHeader) && ((22 <= requestNodeIndex) && (requestNodeIndex <= 23)))) { return this._SortableHeader_22_4; }
    if (((token === import17.TemplateRef) && (31 === requestNodeIndex))) { return this._TemplateRef_31_5; }
    if (((token === import18.NgFor) && (31 === requestNodeIndex))) { return this._NgFor_31_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import11.SimpleChange} = (null as any);
    const valUnwrapper:any = new import11.ValueUnwrapper();
    this.debug(7,4,14);
    const currVal_1:any = 'name';
    if (import8.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._SortableHeader_7_4.fieldName = currVal_1;
      this._expr_1 = currVal_1;
    }
    this.debug(7,4,36);
    const currVal_2:any = this.context.sort;
    if (import8.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._SortableHeader_7_4.sort = currVal_2;
      this._expr_2 = currVal_2;
    }
    this.debug(13,6,14);
    const currVal_3:any = 'network.name';
    if (import8.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._SortableHeader_13_4.fieldName = currVal_3;
      this._expr_3 = currVal_3;
    }
    this.debug(13,6,44);
    const currVal_4:any = this.context.sort;
    if (import8.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._SortableHeader_13_4.sort = currVal_4;
      this._expr_4 = currVal_4;
    }
    this.debug(19,8,14);
    const currVal_5:any = 'status';
    if (import8.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._SortableHeader_19_4.fieldName = currVal_5;
      this._expr_5 = currVal_5;
    }
    this.debug(19,8,38);
    const currVal_6:any = this.context.sort;
    if (import8.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this._SortableHeader_19_4.sort = currVal_6;
      this._expr_6 = currVal_6;
    }
    this.debug(22,9,14);
    const currVal_7:any = 'nextEpisode.airstamp';
    if (import8.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this._SortableHeader_22_4.fieldName = currVal_7;
      this._expr_7 = currVal_7;
    }
    this.debug(22,9,52);
    const currVal_8:any = this.context.sort;
    if (import8.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this._SortableHeader_22_4.sort = currVal_8;
      this._expr_8 = currVal_8;
    }
    this.debug(31,14,8);
    changes = (null as any);
    this.debug(31,14,12);
    valUnwrapper.reset();
    const currVal_9:any = valUnwrapper.unwrap(import8.castByValue(this._pipe_orderBy_0_0,this._pipe_orderBy_0.transform)(this.context.shows,this.context.sort.field,this.context.sort.desc));
    if ((valUnwrapper.hasWrappedValue || import8.checkBinding(throwOnChange,this._expr_9,currVal_9))) {
      this._NgFor_31_6.ngForOf = currVal_9;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import11.SimpleChange(this._expr_9,currVal_9);
      this._expr_9 = currVal_9;
    }
    if ((changes !== (null as any))) { this._NgFor_31_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_31_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.debug(1,1,25);
    const currVal_0:boolean = (!this.context.shows || (this.context.shows.length === 0));
    if (import8.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_1,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
export function viewFactory_ShowList0(viewUtils:import8.ViewUtils,parentInjector:import9.Injector,declarationEl:import6.AppElement):import5.AppView<import1.ShowList> {
  if ((renderType_ShowList === (null as any))) { (renderType_ShowList = viewUtils.createRenderComponentType('/Users/mattlewis/Code/open-source/angular2-tv/src/app/components/showList.ts class ShowList - inline template',0,import14.ViewEncapsulation.None,styles_ShowList,{})); }
  return new _View_ShowList0(viewUtils,parentInjector,declarationEl);
}
const nodeDebugInfos_ShowList1:import0.StaticNodeDebugInfo[] = [
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([import24.Confirm],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([import25.RouterLink],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{})
]
;
class _View_ShowList1 extends import5.DebugAppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _text_19:any;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _text_28:any;
  _text_29:any;
  _el_30:any;
  _text_31:any;
  _el_32:any;
  _text_33:any;
  _text_34:any;
  _el_35:any;
  /*private*/ _appEl_35:import6.AppElement;
  _Confirm_35_5:import24.Confirm;
  _text_36:any;
  _text_37:any;
  _el_38:any;
  _RouterLink_38_3:import25.RouterLink;
  _text_39:any;
  _text_40:any;
  _text_41:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  _pipe_date_1_0:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_20:any;
  _arr_0:any;
  /*private*/ _expr_22:any;
  constructor(viewUtils:import8.ViewUtils,parentInjector:import9.Injector,declarationEl:import6.AppElement) {
    super(_View_ShowList1,renderType_ShowList,import10.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import11.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_ShowList1);
  }
  createInternal(rootSelector:string):import6.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'tr',this.debug(0,14,8));
    this._text_1 = this.renderer.createText(this._el_0,'\n          ',this.debug(1,14,101));
    this._el_2 = this.renderer.createElement(this._el_0,'td',this.debug(2,15,10));
    this._text_3 = this.renderer.createText(this._el_2,'',this.debug(3,15,14));
    this._text_4 = this.renderer.createText(this._el_0,'\n          ',this.debug(4,15,34));
    this._el_5 = this.renderer.createElement(this._el_0,'td',this.debug(5,16,10));
    this._text_6 = this.renderer.createText(this._el_5,'\n            ',this.debug(6,16,14));
    this._el_7 = this.renderer.createElement(this._el_5,'img',this.debug(7,17,12));
    this.renderer.setElementAttribute(this._el_7,'width','60');
    this._text_8 = this.renderer.createText(this._el_5,'\n          ',this.debug(8,17,55));
    this._text_9 = this.renderer.createText(this._el_0,'\n          ',this.debug(9,18,15));
    this._el_10 = this.renderer.createElement(this._el_0,'td',this.debug(10,19,10));
    this._text_11 = this.renderer.createText(this._el_10,'',this.debug(11,19,14));
    this._text_12 = this.renderer.createText(this._el_0,'\n          ',this.debug(12,19,43));
    this._el_13 = this.renderer.createElement(this._el_0,'td',this.debug(13,20,10));
    this._text_14 = this.renderer.createText(this._el_0,'\n          ',this.debug(14,20,46));
    this._el_15 = this.renderer.createElement(this._el_0,'td',this.debug(15,21,10));
    this._text_16 = this.renderer.createText(this._el_15,'\n            ',this.debug(16,21,14));
    this._el_17 = this.renderer.createElement(this._el_15,'span',this.debug(17,22,12));
    this.renderer.setElementAttribute(this._el_17,'class','tag');
    this._text_18 = this.renderer.createText(this._el_17,'',this.debug(18,25,61));
    this._text_19 = this.renderer.createText(this._el_15,'\n          ',this.debug(19,27,20));
    this._text_20 = this.renderer.createText(this._el_0,'\n          ',this.debug(20,28,15));
    this._el_21 = this.renderer.createElement(this._el_0,'td',this.debug(21,29,10));
    this._text_22 = this.renderer.createText(this._el_21,'\n            ',this.debug(22,29,14));
    this._el_23 = this.renderer.createElement(this._el_21,'span',this.debug(23,30,12));
    this._text_24 = this.renderer.createText(this._el_23,'',this.debug(24,30,58));
    this._text_25 = this.renderer.createText(this._el_21,'\n            ',this.debug(25,30,116));
    this._el_26 = this.renderer.createElement(this._el_21,'span',this.debug(26,31,12));
    this._text_27 = this.renderer.createText(this._el_26,'Unknown',this.debug(27,31,57));
    this._text_28 = this.renderer.createText(this._el_21,'\n          ',this.debug(28,31,71));
    this._text_29 = this.renderer.createText(this._el_0,'\n          ',this.debug(29,32,15));
    this._el_30 = this.renderer.createElement(this._el_0,'td',this.debug(30,33,10));
    this.renderer.setElementAttribute(this._el_30,'style','width: 270px');
    this._text_31 = this.renderer.createText(this._el_30,'\n            ',this.debug(31,33,35));
    this._el_32 = this.renderer.createElement(this._el_30,'button',this.debug(32,34,12));
    this.renderer.setElementAttribute(this._el_32,'class','btn btn-success');
    this._text_33 = this.renderer.createText(this._el_32,'\n              Subscribe\n            ',this.debug(33,34,100));
    this._text_34 = this.renderer.createText(this._el_30,'\n            ',this.debug(34,36,21));
    this._el_35 = this.renderer.createElement(this._el_30,'button',this.debug(35,37,12));
    this.renderer.setElementAttribute(this._el_35,'class','btn btn-danger');
    this.renderer.setElementAttribute(this._el_35,'message','Are you sure you would like to unsubscribe from this show?');
    this.renderer.setElementAttribute(this._el_35,'mwlConfirm','');
    this.renderer.setElementAttribute(this._el_35,'title','Unsubscribe');
    this._appEl_35 = new import6.AppElement(35,30,this,this._el_35);
    this._Confirm_35_5 = new import24.Confirm(this._appEl_35.vcRef,new import26.ElementRef(this._el_35),this.parent.parentInjector.get(import2.ConfirmOptions),this.parent.parentInjector.get(import27.ComponentFactoryResolver),this.parent.parentInjector.get(import3.Position),this.renderer,this.parent.parentInjector.get(import28.DOCUMENT));
    this._text_36 = this.renderer.createText(this._el_35,'\n              Unsubscribe\n            ',this.debug(36,43,44));
    this._text_37 = this.renderer.createText(this._el_30,'\n            ',this.debug(37,45,21));
    this._el_38 = this.renderer.createElement(this._el_30,'button',this.debug(38,46,12));
    this.renderer.setElementAttribute(this._el_38,'class','btn btn-info');
    this._RouterLink_38_3 = new import25.RouterLink(this.parent.parentInjector.get(import29.Router),this.parent.parentInjector.get(import30.ActivatedRoute),this.parent.parentInjector.get(import31.LocationStrategy));
    this._text_39 = this.renderer.createText(this._el_38,'\n              Episodes\n            ',this.debug(39,46,79));
    this._text_40 = this.renderer.createText(this._el_30,'\n          ',this.debug(40,48,21));
    this._text_41 = this.renderer.createText(this._el_0,'\n        ',this.debug(41,49,15));
    this._expr_0 = import11.UNINITIALIZED;
    this._expr_1 = import11.UNINITIALIZED;
    this._expr_2 = import11.UNINITIALIZED;
    this._expr_3 = import11.UNINITIALIZED;
    this._expr_4 = import11.UNINITIALIZED;
    this._expr_5 = import11.UNINITIALIZED;
    this._expr_6 = import11.UNINITIALIZED;
    this._expr_7 = import11.UNINITIALIZED;
    this._expr_8 = import11.UNINITIALIZED;
    this._pipe_date_1_0 = import8.pureProxy2((<_View_ShowList0>this.parent)._pipe_date_1.transform.bind((<_View_ShowList0>this.parent)._pipe_date_1));
    this._expr_9 = import11.UNINITIALIZED;
    this._expr_10 = import11.UNINITIALIZED;
    this._expr_12 = import11.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_32,'click',this.eventHandler(this._handle_click_32_0.bind(this)));
    this._expr_18 = import11.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_35,'confirm',this.eventHandler(this._handle_confirm_35_0.bind(this)));
    var disposable_2:Function = this.renderer.listenGlobal('document','click',this.eventHandler(this._handle_click_35_1.bind(this)));
    var disposable_3:Function = this.renderer.listenGlobal('document','touchend',this.eventHandler(this._handle_touchend_35_2.bind(this)));
    var disposable_4:Function = this.renderer.listen(this._el_35,'click',this.eventHandler(this._handle_click_35_3.bind(this)));
    var disposable_5:Function = this.renderer.listenGlobal('window','resize',this.eventHandler(this._handle_resize_35_4.bind(this)));
    this._expr_19 = import11.UNINITIALIZED;
    this._expr_20 = import11.UNINITIALIZED;
    const subscription_0:any = this._Confirm_35_5.confirm.subscribe(this.eventHandler(this._handle_confirm_35_0.bind(this)));
    var disposable_6:Function = this.renderer.listen(this._el_38,'click',this.eventHandler(this._handle_click_38_0.bind(this)));
    this._arr_0 = import8.pureProxy2((p0:any,p1:any):any[] => {
      return [
        p0,
        p1
      ]
      ;
    });
    this._expr_22 = import11.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._text_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._text_40,
      this._text_41
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6
    ]
    ,[subscription_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import24.Confirm) && ((35 <= requestNodeIndex) && (requestNodeIndex <= 36)))) { return this._Confirm_35_5; }
    if (((token === import25.RouterLink) && ((38 <= requestNodeIndex) && (requestNodeIndex <= 39)))) { return this._RouterLink_38_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import11.SimpleChange} = (null as any);
    const valUnwrapper:any = new import11.ValueUnwrapper();
    this.debug(35,37,12);
    changes = (null as any);
    this.debug(35,41,14);
    const currVal_19:any = 'Unsubscribe';
    if (import8.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this._Confirm_35_5.title = currVal_19;
      if ((changes === (null as any))) { (changes = {}); }
      changes['title'] = new import11.SimpleChange(this._expr_19,currVal_19);
      this._expr_19 = currVal_19;
    }
    this.debug(35,42,14);
    const currVal_20:any = 'Are you sure you would like to unsubscribe from this show?';
    if (import8.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this._Confirm_35_5.message = currVal_20;
      if ((changes === (null as any))) { (changes = {}); }
      changes['message'] = new import11.SimpleChange(this._expr_20,currVal_20);
      this._expr_20 = currVal_20;
    }
    if ((changes !== (null as any))) { this._Confirm_35_5.ngOnChanges(changes); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Confirm_35_5.ngOnInit(); }
    this.debug(38,46,41);
    const currVal_22:any = this._arr_0('/episodes',this.context.$implicit.id);
    if (import8.checkBinding(throwOnChange,this._expr_22,currVal_22)) {
      this._RouterLink_38_3.routerLink = currVal_22;
      this._expr_22 = currVal_22;
    }
    this.detectContentChildrenChanges(throwOnChange);
    this.debug(0,14,70);
    const currVal_0:boolean = !((this.context.$implicit.image == (null as any))? (null as any): this.context.$implicit.image.medium);
    if (import8.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_0,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    this.debug(3,15,14);
    const currVal_1:any = import8.interpolate(1,'',this.context.$implicit.name,'');
    if (import8.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setText(this._text_3,currVal_1);
      this._expr_1 = currVal_1;
    }
    this.debug(7,17,17);
    const currVal_2:any = ((this.context.$implicit.image == (null as any))? (null as any): this.context.$implicit.image.medium);
    if (import8.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementProperty(this._el_7,'src',this.viewUtils.sanitizer.sanitize(import32.SecurityContext.URL,currVal_2));
      this._expr_2 = currVal_2;
    }
    this.debug(11,19,14);
    const currVal_3:any = import8.interpolate(1,'',((this.context.$implicit.network == (null as any))? (null as any): this.context.$implicit.network.name),'');
    if (import8.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setText(this._text_11,currVal_3);
      this._expr_3 = currVal_3;
    }
    this.debug(13,20,14);
    const currVal_4:any = this.context.$implicit.summary;
    if (import8.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementProperty(this._el_13,'innerHTML',this.viewUtils.sanitizer.sanitize(import32.SecurityContext.HTML,currVal_4));
      this._expr_4 = currVal_4;
    }
    this.debug(17,24,14);
    const currVal_5:any = (this.context.$implicit.status === 'Running');
    if (import8.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_17,'tag-success',currVal_5);
      this._expr_5 = currVal_5;
    }
    this.debug(17,25,14);
    const currVal_6:any = (this.context.$implicit.status !== 'Running');
    if (import8.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_17,'tag-danger',currVal_6);
      this._expr_6 = currVal_6;
    }
    this.debug(18,25,61);
    const currVal_7:any = import8.interpolate(1,'\n               ',this.context.$implicit.status,'\n             ');
    if (import8.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setText(this._text_18,currVal_7);
      this._expr_7 = currVal_7;
    }
    this.debug(23,30,18);
    const currVal_8:boolean = !((this.context.$implicit == (null as any))? (null as any): ((this.context.$implicit.nextEpisode == (null as any))? (null as any): this.context.$implicit.nextEpisode.airstamp));
    if (import8.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementProperty(this._el_23,'hidden',currVal_8);
      this._expr_8 = currVal_8;
    }
    this.debug(24,30,58);
    valUnwrapper.reset();
    const currVal_9:any = import8.interpolate(1,'',valUnwrapper.unwrap(import8.castByValue(this._pipe_date_1_0,(<_View_ShowList0>this.parent)._pipe_date_1.transform)(((this.context.$implicit == (null as any))? (null as any): ((this.context.$implicit.nextEpisode == (null as any))? (null as any): this.context.$implicit.nextEpisode.airstamp)),'fullDate')),'');
    if ((valUnwrapper.hasWrappedValue || import8.checkBinding(throwOnChange,this._expr_9,currVal_9))) {
      this.renderer.setText(this._text_24,currVal_9);
      this._expr_9 = currVal_9;
    }
    this.debug(26,31,18);
    const currVal_10:any = ((this.context.$implicit == (null as any))? (null as any): ((this.context.$implicit.nextEpisode == (null as any))? (null as any): this.context.$implicit.nextEpisode.airstamp));
    if (import8.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementProperty(this._el_26,'hidden',currVal_10);
      this._expr_10 = currVal_10;
    }
    this.debug(32,34,70);
    const currVal_12:any = this.parent.context.isSubscribed(this.context.$implicit);
    if (import8.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setElementProperty(this._el_32,'hidden',currVal_12);
      this._expr_12 = currVal_12;
    }
    this.debug(35,39,14);
    const currVal_18:boolean = !this.parent.context.isSubscribed(this.context.$implicit);
    if (import8.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementProperty(this._el_35,'hidden',currVal_18);
      this._expr_18 = currVal_18;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this.debug(35,37,12);
    this._Confirm_35_5.ngOnDestroy();
  }
  private _handle_click_32_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(32,34,44);
    const pd_0:any = ((<any>this.parent.context.subscribe(this.context.$implicit)) !== false);
    return (true && pd_0);
  }
  private _handle_confirm_35_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(35,43,14);
    const pd_0:any = ((<any>this.parent.context.unsubscribe(this.context.$implicit)) !== false);
    return (true && pd_0);
  }
  private _handle_click_35_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(35,37,12);
    const pd_0:any = ((<any>this._Confirm_35_5.onDocumentClick($event.target)) !== false);
    return (true && pd_0);
  }
  private _handle_touchend_35_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(35,37,12);
    const pd_0:any = ((<any>this._Confirm_35_5.onDocumentClick($event.target)) !== false);
    return (true && pd_0);
  }
  private _handle_click_35_3($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(35,37,12);
    const pd_0:any = ((<any>this._Confirm_35_5.togglePopover()) !== false);
    return (true && pd_0);
  }
  private _handle_resize_35_4($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(35,37,12);
    const pd_0:any = ((<any>this._Confirm_35_5.onResize()) !== false);
    return (true && pd_0);
  }
  private _handle_click_38_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(38,46,12);
    const pd_0:any = ((<any>this._RouterLink_38_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_ShowList1(viewUtils:import8.ViewUtils,parentInjector:import9.Injector,declarationEl:import6.AppElement):import5.AppView<any> {
  return new _View_ShowList1(viewUtils,parentInjector,declarationEl);
}