/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/debug_context';
import * as import1 from '../../../../src/app/components/sortableHeader';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view';
import * as import4 from '@angular/core/src/linker/element';
import * as import5 from '@angular/core/src/linker/view_utils';
import * as import6 from '@angular/core/src/di/injector';
import * as import7 from '@angular/core/src/linker/view_type';
import * as import8 from '@angular/core/src/change_detection/change_detection';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
const nodeDebugInfos_SortableHeader_Host0:import0.StaticNodeDebugInfo[] = [new import0.StaticNodeDebugInfo([import1.SortableHeader],import1.SortableHeader,{})];
var renderType_SortableHeader_Host:import2.RenderComponentType = (null as any);
class _View_SortableHeader_Host0 extends import3.DebugAppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import4.AppElement;
  _SortableHeader_0_4:import1.SortableHeader;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement) {
    super(_View_SortableHeader_Host0,renderType_SortableHeader_Host,import7.ViewType.HOST,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_SortableHeader_Host0);
  }
  createInternal(rootSelector:string):import4.AppElement {
    this._el_0 = this.selectOrCreateHostElement('th',rootSelector,this.debug(0,0,0));
    this.renderer.setElementAttribute(this._el_0,'sortableHeader','');
    this._appEl_0 = new import4.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_SortableHeader0(this.viewUtils,this.injector(0),this._appEl_0);
    this._SortableHeader_0_4 = new import1.SortableHeader();
    this._appEl_0.initComponent(this._SortableHeader_0_4,[],compView_0);
    compView_0.create(this._SortableHeader_0_4,this.projectableNodes,(null as any));
    this._expr_0 = import8.UNINITIALIZED;
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import1.SortableHeader) && (0 === requestNodeIndex))) { return this._SortableHeader_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.debug(0,0,4);
    const currVal_0:any = '';
    if (import5.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._SortableHeader_0_4.fieldName = currVal_0;
      this._expr_0 = currVal_0;
    }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_SortableHeader_Host0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement):import3.AppView<any> {
  if ((renderType_SortableHeader_Host === (null as any))) { (renderType_SortableHeader_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,[],{})); }
  return new _View_SortableHeader_Host0(viewUtils,parentInjector,declarationEl);
}
export const SortableHeaderNgFactory:import10.ComponentFactory<import1.SortableHeader> = new import10.ComponentFactory<import1.SortableHeader>('th[sortableHeader]',viewFactory_SortableHeader_Host0,import1.SortableHeader);
const styles_SortableHeader:any[] = ['div[_ngcontent-%COMP%] {\n      cursor: pointer;\n      width: 80px;\n    }'];
const nodeDebugInfos_SortableHeader0:import0.StaticNodeDebugInfo[] = [
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{})
]
;
var renderType_SortableHeader:import2.RenderComponentType = (null as any);
class _View_SortableHeader0 extends import3.DebugAppView<import1.SortableHeader> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _text_9:any;
  _text_10:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement) {
    super(_View_SortableHeader0,renderType_SortableHeader,import7.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_SortableHeader0);
  }
  createInternal(rootSelector:string):import4.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n    ',this.debug(0,0,0));
    this._el_1 = this.renderer.createElement(parentRenderNode,'div',this.debug(1,1,4));
    this._text_2 = this.renderer.createText(this._el_1,'\n      ',this.debug(2,1,35));
    this._el_3 = this.renderer.createElement(this._el_1,'i',this.debug(3,2,6));
    this.renderer.setElementAttribute(this._el_3,'class','fa fa-sort');
    this._text_4 = this.renderer.createText(this._el_1,'\n      ',this.debug(4,2,68));
    this._el_5 = this.renderer.createElement(this._el_1,'i',this.debug(5,3,6));
    this.renderer.setElementAttribute(this._el_5,'class','fa fa-sort-asc');
    this._text_6 = this.renderer.createText(this._el_1,'\n      ',this.debug(6,3,85));
    this._el_7 = this.renderer.createElement(this._el_1,'i',this.debug(7,4,6));
    this.renderer.setElementAttribute(this._el_7,'class','fa fa-sort-desc');
    this._text_8 = this.renderer.createText(this._el_1,'\n      ',this.debug(8,4,87));
    this.debug((null as any),5,6);
    this.renderer.projectNodes(this._el_1,import5.flattenNestedViewRenderNodes(this.projectableNodes[0]));
    this._text_9 = this.renderer.createText(this._el_1,'\n    ',this.debug(9,5,31));
    this._text_10 = this.renderer.createText(parentRenderNode,'\n  ',this.debug(10,6,10));
    var disposable_0:Function = this.renderer.listen(this._el_1,'click',this.eventHandler(this._handle_click_1_0.bind(this)));
    this._expr_1 = import8.UNINITIALIZED;
    this._expr_2 = import8.UNINITIALIZED;
    this._expr_3 = import8.UNINITIALIZED;
    this.init([],[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._text_10
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    this.debug(3,2,28);
    const currVal_1:any = (this.context.sort.field === this.context.fieldName);
    if (import5.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_3,'hidden',currVal_1);
      this._expr_1 = currVal_1;
    }
    this.debug(5,3,32);
    const currVal_2:any = ((this.context.sort.field !== this.context.fieldName) || this.context.sort.desc);
    if (import5.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementProperty(this._el_5,'hidden',currVal_2);
      this._expr_2 = currVal_2;
    }
    this.debug(7,4,33);
    const currVal_3:any = ((this.context.sort.field !== this.context.fieldName) || !this.context.sort.desc);
    if (import5.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementProperty(this._el_7,'hidden',currVal_3);
      this._expr_3 = currVal_3;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_1_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(1,1,9);
    const pd_0:any = ((<any>this.context.headerClicked()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_SortableHeader0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement):import3.AppView<import1.SortableHeader> {
  if ((renderType_SortableHeader === (null as any))) { (renderType_SortableHeader = viewUtils.createRenderComponentType('/Users/mattlewis/Code/open-source/angular2-tv/src/app/components/sortableHeader.ts class SortableHeader - inline template',1,import9.ViewEncapsulation.Emulated,styles_SortableHeader,{})); }
  return new _View_SortableHeader0(viewUtils,parentInjector,declarationEl);
}