/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/debug_context';
import * as import1 from '../../../../src/app/components/subscribedShows';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view';
import * as import4 from '@angular/core/src/linker/element';
import * as import5 from '@angular/core/src/linker/view_utils';
import * as import6 from '@angular/core/src/di/injector';
import * as import7 from '@angular/core/src/linker/view_type';
import * as import8 from '@angular/core/src/change_detection/change_detection';
import * as import9 from '../../../../src/app/providers/localStorage';
import * as import10 from '@angular/core/src/metadata/view';
import * as import11 from '@angular/core/src/linker/component_factory';
import * as import12 from '../../../../src/app/components/showList';
import * as import13 from 'angular2-bootstrap-confirm/dist/esm/src/confirmOptions.provider';
import * as import14 from 'angular2-bootstrap-confirm/dist/esm/src/position.provider';
import * as import15 from '@angular/router/src/directives/router_link';
import * as import16 from '@ng-bootstrap/ng-bootstrap/util/positioning';
import * as import17 from './showList.ngfactory';
import * as import18 from '../../../../src/app/providers/tvMaze';
import * as import19 from '@angular/router/src/router';
import * as import20 from '@angular/router/src/router_state';
import * as import21 from '@angular/common/src/location/location_strategy';
import * as import22 from '@angular/core/src/security';
const nodeDebugInfos_SubscribedShows_Host0:import0.StaticNodeDebugInfo[] = [new import0.StaticNodeDebugInfo([import1.SubscribedShows],import1.SubscribedShows,{})];
var renderType_SubscribedShows_Host:import2.RenderComponentType = (null as any);
class _View_SubscribedShows_Host0 extends import3.DebugAppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import4.AppElement;
  _SubscribedShows_0_4:import1.SubscribedShows;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement) {
    super(_View_SubscribedShows_Host0,renderType_SubscribedShows_Host,import7.ViewType.HOST,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_SubscribedShows_Host0);
  }
  createInternal(rootSelector:string):import4.AppElement {
    this._el_0 = this.selectOrCreateHostElement('subscribed-shows',rootSelector,this.debug(0,0,0));
    this._appEl_0 = new import4.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_SubscribedShows0(this.viewUtils,this.injector(0),this._appEl_0);
    this._SubscribedShows_0_4 = new import1.SubscribedShows(this.parentInjector.get(import9.LocalStorage));
    this._appEl_0.initComponent(this._SubscribedShows_0_4,[],compView_0);
    compView_0.create(this._SubscribedShows_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import1.SubscribedShows) && (0 === requestNodeIndex))) { return this._SubscribedShows_0_4; }
    return notFoundResult;
  }
}
function viewFactory_SubscribedShows_Host0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement):import3.AppView<any> {
  if ((renderType_SubscribedShows_Host === (null as any))) { (renderType_SubscribedShows_Host = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,[],{})); }
  return new _View_SubscribedShows_Host0(viewUtils,parentInjector,declarationEl);
}
export const SubscribedShowsNgFactory:import11.ComponentFactory<import1.SubscribedShows> = new import11.ComponentFactory<import1.SubscribedShows>('subscribed-shows',viewFactory_SubscribedShows_Host0,import1.SubscribedShows);
const styles_SubscribedShows:any[] = [];
const nodeDebugInfos_SubscribedShows0:import0.StaticNodeDebugInfo[] = [
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([
    import12.ShowList,
    import13.ConfirmOptions,
    import14.Position
  ]
  ,import12.ShowList,{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([import15.RouterLinkWithHref],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{})
]
;
var renderType_SubscribedShows:import2.RenderComponentType = (null as any);
class _View_SubscribedShows0 extends import3.DebugAppView<import1.SubscribedShows> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import4.AppElement;
  _ShowList_4_4:import12.ShowList;
  __ConfirmOptions_4_5:any;
  __Position_4_6:import16.Positioning;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _RouterLinkWithHref_8_3:import15.RouterLinkWithHref;
  _text_9:any;
  _text_10:any;
  _text_11:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  _arr_0:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement) {
    super(_View_SubscribedShows0,renderType_SubscribedShows,import7.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_SubscribedShows0);
  }
  get _ConfirmOptions_4_5():any {
    this.debug(4,2,4);
    if ((this.__ConfirmOptions_4_5 == (null as any))) { (this.__ConfirmOptions_4_5 = import12.confirmOptionsFactory()); }
    return this.__ConfirmOptions_4_5;
  }
  get _Position_4_6():import16.Positioning {
    this.debug(4,2,4);
    if ((this.__Position_4_6 == (null as any))) { (this.__Position_4_6 = new import16.Positioning()); }
    return this.__Position_4_6;
  }
  createInternal(rootSelector:string):import4.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n    ',this.debug(0,0,0));
    this._el_1 = this.renderer.createElement(parentRenderNode,'h1',this.debug(1,1,4));
    this._text_2 = this.renderer.createText(this._el_1,'Subscribed shows',this.debug(2,1,8));
    this._text_3 = this.renderer.createText(parentRenderNode,'\n    ',this.debug(3,1,29));
    this._el_4 = this.renderer.createElement(parentRenderNode,'show-list',this.debug(4,2,4));
    this._appEl_4 = new import4.AppElement(4,(null as any),this,this._el_4);
    var compView_4:any = import17.viewFactory_ShowList0(this.viewUtils,this.injector(4),this._appEl_4);
    this._ShowList_4_4 = new import12.ShowList(this.parentInjector.get(import9.LocalStorage),this.parentInjector.get(import18.TVMaze));
    this._appEl_4.initComponent(this._ShowList_4_4,[],compView_4);
    compView_4.create(this._ShowList_4_4,[],(null as any));
    this._text_5 = this.renderer.createText(parentRenderNode,'\n    ',this.debug(5,2,89));
    this._el_6 = this.renderer.createElement(parentRenderNode,'div',this.debug(6,3,4));
    this.renderer.setElementAttribute(this._el_6,'class','alert alert-warning');
    this._text_7 = this.renderer.createText(this._el_6,'\n      You haven\'t yet subscribed to any shows. ',this.debug(7,5,44));
    this._el_8 = this.renderer.createElement(this._el_6,'a',this.debug(8,6,47));
    this._RouterLinkWithHref_8_3 = new import15.RouterLinkWithHref(this.parentInjector.get(import19.Router),this.parentInjector.get(import20.ActivatedRoute),this.parentInjector.get(import21.LocationStrategy));
    this._text_9 = this.renderer.createText(this._el_8,'Add some now.',this.debug(9,6,74));
    this._text_10 = this.renderer.createText(this._el_6,'\n    ',this.debug(10,6,91));
    this._text_11 = this.renderer.createText(parentRenderNode,'\n  ',this.debug(11,7,10));
    var disposable_0:Function = this.renderer.listen(this._el_4,'unsubscribe',this.eventHandler(this._handle_unsubscribe_4_0.bind(this)));
    this._expr_1 = import8.UNINITIALIZED;
    const subscription_0:any = this._ShowList_4_4.unsubscribeCallback.subscribe(this.eventHandler(this._handle_unsubscribe_4_0.bind(this)));
    this._expr_2 = import8.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_8,'click',this.eventHandler(this._handle_click_8_0.bind(this)));
    this._arr_0 = import5.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._expr_4 = import8.UNINITIALIZED;
    this._expr_5 = import8.UNINITIALIZED;
    this.init([],[
      this._text_0,
      this._el_1,
      this._text_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._text_11
    ]
    ,[
      disposable_0,
      disposable_1
    ]
    ,[subscription_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import12.ShowList) && (4 === requestNodeIndex))) { return this._ShowList_4_4; }
    if (((token === import13.ConfirmOptions) && (4 === requestNodeIndex))) { return this._ConfirmOptions_4_5; }
    if (((token === import14.Position) && (4 === requestNodeIndex))) { return this._Position_4_6; }
    if (((token === import15.RouterLinkWithHref) && ((8 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._RouterLinkWithHref_8_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import8.SimpleChange} = (null as any);
    this.debug(4,2,4);
    changes = (null as any);
    this.debug(4,2,15);
    const currVal_1:any = this.context.subscribedShows;
    if (import5.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._ShowList_4_4.shows = currVal_1;
      if ((changes === (null as any))) { (changes = {}); }
      changes['shows'] = new import8.SimpleChange(this._expr_1,currVal_1);
      this._expr_1 = currVal_1;
    }
    if ((changes !== (null as any))) { this._ShowList_4_4.ngOnChanges(changes); }
    this.debug(8,6,47);
    changes = (null as any);
    this.debug(8,6,50);
    const currVal_4:any = this._arr_0('/add');
    if (import5.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._RouterLinkWithHref_8_3.routerLink = currVal_4;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import8.SimpleChange(this._expr_4,currVal_4);
      this._expr_4 = currVal_4;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_8_3.ngOnChanges(changes); }
    this.detectContentChildrenChanges(throwOnChange);
    this.debug(6,5,6);
    const currVal_2:any = (this.context.subscribedShows.length > 0);
    if (import5.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementProperty(this._el_6,'hidden',currVal_2);
      this._expr_2 = currVal_2;
    }
    this.debug(8,6,47);
    const currVal_5:any = this._RouterLinkWithHref_8_3.href;
    if (import5.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementProperty(this._el_8,'href',this.viewUtils.sanitizer.sanitize(import22.SecurityContext.URL,currVal_5));
      this._expr_5 = currVal_5;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this.debug(8,6,47);
    this._RouterLinkWithHref_8_3.ngOnDestroy();
  }
  private _handle_unsubscribe_4_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(4,2,41);
    const pd_0:any = ((<any>this.context.unsubscribe($event)) !== false);
    return (true && pd_0);
  }
  private _handle_click_8_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(8,6,47);
    const pd_0:any = ((<any>this._RouterLinkWithHref_8_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_SubscribedShows0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement):import3.AppView<import1.SubscribedShows> {
  if ((renderType_SubscribedShows === (null as any))) { (renderType_SubscribedShows = viewUtils.createRenderComponentType('/Users/mattlewis/Code/open-source/angular2-tv/src/app/components/subscribedShows.ts class SubscribedShows - inline template',0,import10.ViewEncapsulation.None,styles_SubscribedShows,{})); }
  return new _View_SubscribedShows0(viewUtils,parentInjector,declarationEl);
}