/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/debug_context';
import * as import1 from '../../../src/app/app.component';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view';
import * as import4 from '@angular/core/src/linker/element';
import * as import5 from '@angular/core/src/linker/view_utils';
import * as import6 from '@angular/core/src/di/injector';
import * as import7 from '@angular/core/src/linker/view_type';
import * as import8 from '@angular/core/src/change_detection/change_detection';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from '../../../src/app/components/navbar';
import * as import12 from '@angular/router/src/directives/router_outlet';
import * as import13 from './components/navbar.ngfactory';
import * as import14 from '@angular/common/src/location/location';
import * as import15 from '@angular/router/src/router_outlet_map';
import * as import16 from '@angular/core/src/linker/component_factory_resolver';
const nodeDebugInfos_AppComponent_Host0:import0.StaticNodeDebugInfo[] = [new import0.StaticNodeDebugInfo([import1.AppComponent],import1.AppComponent,{})];
var renderType_AppComponent_Host:import2.RenderComponentType = (null as any);
class _View_AppComponent_Host0 extends import3.DebugAppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import4.AppElement;
  _AppComponent_0_4:import1.AppComponent;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement) {
    super(_View_AppComponent_Host0,renderType_AppComponent_Host,import7.ViewType.HOST,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_AppComponent_Host0);
  }
  createInternal(rootSelector:string):import4.AppElement {
    this._el_0 = this.selectOrCreateHostElement('app',rootSelector,this.debug(0,0,0));
    this._appEl_0 = new import4.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_AppComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._AppComponent_0_4 = new import1.AppComponent();
    this._appEl_0.initComponent(this._AppComponent_0_4,[],compView_0);
    compView_0.create(this._AppComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import1.AppComponent) && (0 === requestNodeIndex))) { return this._AppComponent_0_4; }
    return notFoundResult;
  }
}
function viewFactory_AppComponent_Host0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement):import3.AppView<any> {
  if ((renderType_AppComponent_Host === (null as any))) { (renderType_AppComponent_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,[],{})); }
  return new _View_AppComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const AppComponentNgFactory:import10.ComponentFactory<import1.AppComponent> = new import10.ComponentFactory<import1.AppComponent>('app',viewFactory_AppComponent_Host0,import1.AppComponent);
const styles_AppComponent:any[] = ['.container[_ngcontent-%COMP%] {\n      padding-top: 70px;\n    }'];
const nodeDebugInfos_AppComponent0:import0.StaticNodeDebugInfo[] = [
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([import11.Navbar],import11.Navbar,{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([import12.RouterOutlet],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{})
]
;
var renderType_AppComponent:import2.RenderComponentType = (null as any);
class _View_AppComponent0 extends import3.DebugAppView<import1.AppComponent> {
  _text_0:any;
  _el_1:any;
  /*private*/ _appEl_1:import4.AppElement;
  _Navbar_1_4:import11.Navbar;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _el_5:any;
  /*private*/ _appEl_5:import4.AppElement;
  _RouterOutlet_5_5:import12.RouterOutlet;
  _text_6:any;
  _text_7:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement) {
    super(_View_AppComponent0,renderType_AppComponent,import7.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_AppComponent0);
  }
  createInternal(rootSelector:string):import4.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n    ',this.debug(0,0,0));
    this._el_1 = this.renderer.createElement(parentRenderNode,'navbar',this.debug(1,1,4));
    this._appEl_1 = new import4.AppElement(1,(null as any),this,this._el_1);
    var compView_1:any = import13.viewFactory_Navbar0(this.viewUtils,this.injector(1),this._appEl_1);
    this._Navbar_1_4 = new import11.Navbar(this.parentInjector.get(import14.Location));
    this._appEl_1.initComponent(this._Navbar_1_4,[],compView_1);
    compView_1.create(this._Navbar_1_4,[],(null as any));
    this._text_2 = this.renderer.createText(parentRenderNode,'\n    ',this.debug(2,1,21));
    this._el_3 = this.renderer.createElement(parentRenderNode,'div',this.debug(3,2,4));
    this.renderer.setElementAttribute(this._el_3,'class','container');
    this._text_4 = this.renderer.createText(this._el_3,'\n      ',this.debug(4,2,27));
    this._el_5 = this.renderer.createElement(this._el_3,'router-outlet',this.debug(5,3,6));
    this._appEl_5 = new import4.AppElement(5,3,this,this._el_5);
    this._RouterOutlet_5_5 = new import12.RouterOutlet(this.parentInjector.get(import15.RouterOutletMap),this._appEl_5.vcRef,this.parentInjector.get(import16.ComponentFactoryResolver),(null as any));
    this._text_6 = this.renderer.createText(this._el_3,'\n    ',this.debug(6,3,37));
    this._text_7 = this.renderer.createText(parentRenderNode,'\n  ',this.debug(7,4,10));
    this.init([],[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import11.Navbar) && (1 === requestNodeIndex))) { return this._Navbar_1_4; }
    if (((token === import12.RouterOutlet) && (5 === requestNodeIndex))) { return this._RouterOutlet_5_5; }
    return notFoundResult;
  }
  destroyInternal():void {
    this.debug(5,3,6);
    this._RouterOutlet_5_5.ngOnDestroy();
  }
}
export function viewFactory_AppComponent0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement):import3.AppView<import1.AppComponent> {
  if ((renderType_AppComponent === (null as any))) { (renderType_AppComponent = viewUtils.createRenderComponentType('/Users/mattlewis/Code/open-source/angular2-tv/src/app/app.component.ts class AppComponent - inline template',0,import9.ViewEncapsulation.Emulated,styles_AppComponent,{})); }
  return new _View_AppComponent0(viewUtils,parentInjector,declarationEl);
}