/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from '../../../src/app/app.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/core/src/application_module';
import * as import4 from '@angular/platform-browser/src/browser';
import * as import5 from '@angular/router/src/router_module';
import * as import6 from '@angular/forms/src/directives';
import * as import7 from '@angular/forms/src/form_providers';
import * as import8 from '@angular/http/src/http_module';
import * as import9 from 'angular2-bootstrap-confirm/dist/esm/src/confirm.module';
import * as import10 from 'angular2-calendar/dist/esm/src/calendar.module';
import * as import11 from '@angular/common/src/localization';
import * as import12 from '@angular/core/src/application_init';
import * as import13 from '@angular/core/src/testability/testability';
import * as import14 from '@angular/core/src/application_ref';
import * as import15 from '@angular/core/src/linker/compiler';
import * as import16 from '@angular/platform-browser/src/dom/events/hammer_gestures';
import * as import17 from '@angular/platform-browser/src/dom/events/event_manager';
import * as import18 from '@angular/platform-browser/src/dom/shared_styles_host';
import * as import19 from '@angular/platform-browser/src/dom/dom_renderer';
import * as import20 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import21 from '@angular/core/src/linker/view_utils';
import * as import22 from '@angular/platform-browser/src/browser/title';
import * as import23 from '@angular/forms/src/form_builder';
import * as import24 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import25 from '@angular/http/src/backends/browser_xhr';
import * as import26 from '@angular/http/src/base_response_options';
import * as import27 from '@angular/http/src/backends/xhr_backend';
import * as import28 from '@angular/http/src/base_request_options';
import * as import29 from 'angular2-calendar/dist/esm/src/providers/calendarEventTitle.provider';
import * as import30 from 'angular2-calendar/dist/esm/src/providers/calendarDateFormatter.provider';
import * as import31 from '@angular/common/src/location/location';
import * as import32 from '@angular/router/src/url_tree';
import * as import33 from '@angular/router/src/router_outlet_map';
import * as import34 from '@angular/core/src/linker/system_js_ng_module_factory_loader';
import * as import35 from '../../../src/app/providers/localStorage';
import * as import36 from '../../../src/app/providers/tvMaze';
import * as import37 from '@angular/core/src/di/injector';
import * as import38 from '../../node_modules/angular2-bootstrap-confirm/dist/esm/src/confirmPopover.component.ngfactory';
import * as import39 from '../../node_modules/angular2-calendar/dist/esm/src/directives/calendarTooltip.directive.ngfactory';
import * as import40 from './components/subscribedShows.ngfactory';
import * as import41 from './components/episodes.ngfactory';
import * as import42 from './components/searchShows.ngfactory';
import * as import43 from './components/scheduleCalendar.ngfactory';
import * as import44 from './app.component.ngfactory';
import * as import45 from '@angular/core/src/application_tokens';
import * as import46 from '@angular/platform-browser/src/dom/events/dom_events';
import * as import47 from '@angular/platform-browser/src/dom/events/key_events';
import * as import48 from '@angular/core/src/zone/ng_zone';
import * as import49 from '@angular/platform-browser/src/dom/debug/ng_probe';
import * as import50 from '@angular/common/src/location/platform_location';
import * as import51 from '@angular/common/src/location/location_strategy';
import * as import52 from '../../../src/app/components/subscribedShows';
import * as import53 from '../../../src/app/components/episodes';
import * as import54 from '../../../src/app/components/searchShows';
import * as import55 from '../../../src/app/components/scheduleCalendar';
import * as import56 from '@angular/router/src/router';
import * as import57 from '@angular/core/src/console';
import * as import58 from '@angular/core/src/i18n/tokens';
import * as import59 from '@angular/core/src/error_handler';
import * as import60 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import61 from '@angular/platform-browser/src/dom/animation_driver';
import * as import62 from '@angular/core/src/render/api';
import * as import63 from '@angular/core/src/security';
import * as import64 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import65 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import66 from '@angular/http/src/interfaces';
import * as import67 from '@angular/http/src/http';
import * as import68 from '@angular/core/src/linker/ng_module_factory_loader';
import * as import69 from '@angular/router/src/router_config_loader';
import * as import70 from '@angular/router/src/router_state';
class AppModuleInjector extends import0.NgModuleInjector<import1.AppModule> {
  _CommonModule_0:import2.CommonModule;
  _ApplicationModule_1:import3.ApplicationModule;
  _BrowserModule_2:import4.BrowserModule;
  _ROUTER_FORROOT_GUARD_3:any;
  _RouterModule_4:import5.RouterModule;
  _InternalFormsSharedModule_5:import6.InternalFormsSharedModule;
  _ReactiveFormsModule_6:import7.ReactiveFormsModule;
  _HttpModule_7:import8.HttpModule;
  _ConfirmModule_8:import9.ConfirmModule;
  _CalendarModule_9:import10.CalendarModule;
  _AppModule_10:import1.AppModule;
  __LOCALE_ID_11:any;
  __NgLocalization_12:import11.NgLocaleLocalization;
  _ErrorHandler_13:any;
  _ApplicationInitStatus_14:import12.ApplicationInitStatus;
  _Testability_15:import13.Testability;
  _ApplicationRef__16:import14.ApplicationRef_;
  __ApplicationRef_17:any;
  __Compiler_18:import15.Compiler;
  __APP_ID_19:any;
  __DOCUMENT_20:any;
  __HAMMER_GESTURE_CONFIG_21:import16.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_22:any[];
  __EventManager_23:import17.EventManager;
  __DomSharedStylesHost_24:import18.DomSharedStylesHost;
  __AnimationDriver_25:any;
  __DomRootRenderer_26:import19.DomRootRenderer_;
  __RootRenderer_27:any;
  __DomSanitizer_28:import20.DomSanitizerImpl;
  __Sanitizer_29:any;
  __ViewUtils_30:import21.ViewUtils;
  __IterableDiffers_31:any;
  __KeyValueDiffers_32:any;
  __SharedStylesHost_33:any;
  __Title_34:import22.Title;
  __FormBuilder_35:import23.FormBuilder;
  __RadioControlRegistry_36:import24.RadioControlRegistry;
  __BrowserXhr_37:import25.BrowserXhr;
  __ResponseOptions_38:import26.BaseResponseOptions;
  __XSRFStrategy_39:any;
  __XHRBackend_40:import27.XHRBackend;
  __RequestOptions_41:import28.BaseRequestOptions;
  __Http_42:any;
  __CalendarEventTitle_43:import29.CalendarEventTitle;
  __CalendarDateFormatter_44:import30.CalendarDateFormatter;
  __ROUTER_CONFIGURATION_45:any;
  __LocationStrategy_46:any;
  __Location_47:import31.Location;
  __UrlSerializer_48:import32.DefaultUrlSerializer;
  __RouterOutletMap_49:import33.RouterOutletMap;
  __NgModuleFactoryLoader_50:import34.SystemJsNgModuleLoader;
  __ROUTES_51:any[];
  __Router_52:any;
  __ActivatedRoute_53:any;
  __APP_BOOTSTRAP_LISTENER_54:any[];
  __LocalStorage_55:import35.LocalStorage;
  __TVMaze_56:import36.TVMaze;
  constructor(parent:import37.Injector) {
    super(parent,[
      import38.ConfirmPopoverNgFactory,
      import39.CalendarTooltipWindowComponentNgFactory,
      import40.SubscribedShowsNgFactory,
      import41.EpisodesNgFactory,
      import42.SearchShowsNgFactory,
      import43.ScheduleCalendarNgFactory,
      import44.AppComponentNgFactory
    ]
    ,[import44.AppComponentNgFactory]);
  }
  get _LOCALE_ID_11():any {
    if ((this.__LOCALE_ID_11 == (null as any))) { (this.__LOCALE_ID_11 = 'en-US'); }
    return this.__LOCALE_ID_11;
  }
  get _NgLocalization_12():import11.NgLocaleLocalization {
    if ((this.__NgLocalization_12 == (null as any))) { (this.__NgLocalization_12 = new import11.NgLocaleLocalization(this._LOCALE_ID_11)); }
    return this.__NgLocalization_12;
  }
  get _ApplicationRef_17():any {
    if ((this.__ApplicationRef_17 == (null as any))) { (this.__ApplicationRef_17 = this._ApplicationRef__16); }
    return this.__ApplicationRef_17;
  }
  get _Compiler_18():import15.Compiler {
    if ((this.__Compiler_18 == (null as any))) { (this.__Compiler_18 = new import15.Compiler()); }
    return this.__Compiler_18;
  }
  get _APP_ID_19():any {
    if ((this.__APP_ID_19 == (null as any))) { (this.__APP_ID_19 = import45._appIdRandomProviderFactory()); }
    return this.__APP_ID_19;
  }
  get _DOCUMENT_20():any {
    if ((this.__DOCUMENT_20 == (null as any))) { (this.__DOCUMENT_20 = import4._document()); }
    return this.__DOCUMENT_20;
  }
  get _HAMMER_GESTURE_CONFIG_21():import16.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_21 == (null as any))) { (this.__HAMMER_GESTURE_CONFIG_21 = new import16.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_21;
  }
  get _EVENT_MANAGER_PLUGINS_22():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_22 == (null as any))) { (this.__EVENT_MANAGER_PLUGINS_22 = [
      new import46.DomEventsPlugin(),
      new import47.KeyEventsPlugin(),
      new import16.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_21)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_22;
  }
  get _EventManager_23():import17.EventManager {
    if ((this.__EventManager_23 == (null as any))) { (this.__EventManager_23 = new import17.EventManager(this._EVENT_MANAGER_PLUGINS_22,this.parent.get(import48.NgZone))); }
    return this.__EventManager_23;
  }
  get _DomSharedStylesHost_24():import18.DomSharedStylesHost {
    if ((this.__DomSharedStylesHost_24 == (null as any))) { (this.__DomSharedStylesHost_24 = new import18.DomSharedStylesHost(this._DOCUMENT_20)); }
    return this.__DomSharedStylesHost_24;
  }
  get _AnimationDriver_25():any {
    if ((this.__AnimationDriver_25 == (null as any))) { (this.__AnimationDriver_25 = import4._resolveDefaultAnimationDriver()); }
    return this.__AnimationDriver_25;
  }
  get _DomRootRenderer_26():import19.DomRootRenderer_ {
    if ((this.__DomRootRenderer_26 == (null as any))) { (this.__DomRootRenderer_26 = new import19.DomRootRenderer_(this._DOCUMENT_20,this._EventManager_23,this._DomSharedStylesHost_24,this._AnimationDriver_25)); }
    return this.__DomRootRenderer_26;
  }
  get _RootRenderer_27():any {
    if ((this.__RootRenderer_27 == (null as any))) { (this.__RootRenderer_27 = import49._createConditionalRootRenderer(this._DomRootRenderer_26,this.parent.get(import49.NgProbeToken,(null as any)))); }
    return this.__RootRenderer_27;
  }
  get _DomSanitizer_28():import20.DomSanitizerImpl {
    if ((this.__DomSanitizer_28 == (null as any))) { (this.__DomSanitizer_28 = new import20.DomSanitizerImpl()); }
    return this.__DomSanitizer_28;
  }
  get _Sanitizer_29():any {
    if ((this.__Sanitizer_29 == (null as any))) { (this.__Sanitizer_29 = this._DomSanitizer_28); }
    return this.__Sanitizer_29;
  }
  get _ViewUtils_30():import21.ViewUtils {
    if ((this.__ViewUtils_30 == (null as any))) { (this.__ViewUtils_30 = new import21.ViewUtils(this._RootRenderer_27,this._APP_ID_19,this._Sanitizer_29)); }
    return this.__ViewUtils_30;
  }
  get _IterableDiffers_31():any {
    if ((this.__IterableDiffers_31 == (null as any))) { (this.__IterableDiffers_31 = import3._iterableDiffersFactory()); }
    return this.__IterableDiffers_31;
  }
  get _KeyValueDiffers_32():any {
    if ((this.__KeyValueDiffers_32 == (null as any))) { (this.__KeyValueDiffers_32 = import3._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_32;
  }
  get _SharedStylesHost_33():any {
    if ((this.__SharedStylesHost_33 == (null as any))) { (this.__SharedStylesHost_33 = this._DomSharedStylesHost_24); }
    return this.__SharedStylesHost_33;
  }
  get _Title_34():import22.Title {
    if ((this.__Title_34 == (null as any))) { (this.__Title_34 = new import22.Title()); }
    return this.__Title_34;
  }
  get _FormBuilder_35():import23.FormBuilder {
    if ((this.__FormBuilder_35 == (null as any))) { (this.__FormBuilder_35 = new import23.FormBuilder()); }
    return this.__FormBuilder_35;
  }
  get _RadioControlRegistry_36():import24.RadioControlRegistry {
    if ((this.__RadioControlRegistry_36 == (null as any))) { (this.__RadioControlRegistry_36 = new import24.RadioControlRegistry()); }
    return this.__RadioControlRegistry_36;
  }
  get _BrowserXhr_37():import25.BrowserXhr {
    if ((this.__BrowserXhr_37 == (null as any))) { (this.__BrowserXhr_37 = new import25.BrowserXhr()); }
    return this.__BrowserXhr_37;
  }
  get _ResponseOptions_38():import26.BaseResponseOptions {
    if ((this.__ResponseOptions_38 == (null as any))) { (this.__ResponseOptions_38 = new import26.BaseResponseOptions()); }
    return this.__ResponseOptions_38;
  }
  get _XSRFStrategy_39():any {
    if ((this.__XSRFStrategy_39 == (null as any))) { (this.__XSRFStrategy_39 = import8._createDefaultCookieXSRFStrategy()); }
    return this.__XSRFStrategy_39;
  }
  get _XHRBackend_40():import27.XHRBackend {
    if ((this.__XHRBackend_40 == (null as any))) { (this.__XHRBackend_40 = new import27.XHRBackend(this._BrowserXhr_37,this._ResponseOptions_38,this._XSRFStrategy_39)); }
    return this.__XHRBackend_40;
  }
  get _RequestOptions_41():import28.BaseRequestOptions {
    if ((this.__RequestOptions_41 == (null as any))) { (this.__RequestOptions_41 = new import28.BaseRequestOptions()); }
    return this.__RequestOptions_41;
  }
  get _Http_42():any {
    if ((this.__Http_42 == (null as any))) { (this.__Http_42 = import8.httpFactory(this._XHRBackend_40,this._RequestOptions_41)); }
    return this.__Http_42;
  }
  get _CalendarEventTitle_43():import29.CalendarEventTitle {
    if ((this.__CalendarEventTitle_43 == (null as any))) { (this.__CalendarEventTitle_43 = new import29.CalendarEventTitle()); }
    return this.__CalendarEventTitle_43;
  }
  get _CalendarDateFormatter_44():import30.CalendarDateFormatter {
    if ((this.__CalendarDateFormatter_44 == (null as any))) { (this.__CalendarDateFormatter_44 = new import30.CalendarDateFormatter()); }
    return this.__CalendarDateFormatter_44;
  }
  get _ROUTER_CONFIGURATION_45():any {
    if ((this.__ROUTER_CONFIGURATION_45 == (null as any))) { (this.__ROUTER_CONFIGURATION_45 = {useHash: true}); }
    return this.__ROUTER_CONFIGURATION_45;
  }
  get _LocationStrategy_46():any {
    if ((this.__LocationStrategy_46 == (null as any))) { (this.__LocationStrategy_46 = import5.provideLocationStrategy(this.parent.get(import50.PlatformLocation),this.parent.get(import51.APP_BASE_HREF,(null as any)),this._ROUTER_CONFIGURATION_45)); }
    return this.__LocationStrategy_46;
  }
  get _Location_47():import31.Location {
    if ((this.__Location_47 == (null as any))) { (this.__Location_47 = new import31.Location(this._LocationStrategy_46)); }
    return this.__Location_47;
  }
  get _UrlSerializer_48():import32.DefaultUrlSerializer {
    if ((this.__UrlSerializer_48 == (null as any))) { (this.__UrlSerializer_48 = new import32.DefaultUrlSerializer()); }
    return this.__UrlSerializer_48;
  }
  get _RouterOutletMap_49():import33.RouterOutletMap {
    if ((this.__RouterOutletMap_49 == (null as any))) { (this.__RouterOutletMap_49 = new import33.RouterOutletMap()); }
    return this.__RouterOutletMap_49;
  }
  get _NgModuleFactoryLoader_50():import34.SystemJsNgModuleLoader {
    if ((this.__NgModuleFactoryLoader_50 == (null as any))) { (this.__NgModuleFactoryLoader_50 = new import34.SystemJsNgModuleLoader(this._Compiler_18,this.parent.get(import34.SystemJsNgModuleLoaderConfig,(null as any)))); }
    return this.__NgModuleFactoryLoader_50;
  }
  get _ROUTES_51():any[] {
      if ((this.__ROUTES_51 == (null as any))) { (this.__ROUTES_51 = [[
        {
          path: '',
          component: import52.SubscribedShows
        }
        ,
        {
          path: 'episodes/:id',
          component: import53.Episodes
        }
        ,
        {
          path: 'add',
          component: import54.SearchShows
        }
        ,
        {
          path: 'schedule',
          component: import55.ScheduleCalendar
        }
        ,
        {
          path: '**',
          redirectTo: ''
        }

      ]
    ]); }
    return this.__ROUTES_51;
  }
  get _Router_52():any {
    if ((this.__Router_52 == (null as any))) { (this.__Router_52 = import5.setupRouter(this._ApplicationRef_17,this._UrlSerializer_48,this._RouterOutletMap_49,this._Location_47,this,this._NgModuleFactoryLoader_50,this._Compiler_18,this._ROUTES_51,this._ROUTER_CONFIGURATION_45)); }
    return this.__Router_52;
  }
  get _ActivatedRoute_53():any {
    if ((this.__ActivatedRoute_53 == (null as any))) { (this.__ActivatedRoute_53 = import5.rootRoute(this._Router_52)); }
    return this.__ActivatedRoute_53;
  }
  get _APP_BOOTSTRAP_LISTENER_54():any[] {
    if ((this.__APP_BOOTSTRAP_LISTENER_54 == (null as any))) { (this.__APP_BOOTSTRAP_LISTENER_54 = [import5.initialRouterNavigation(this._Router_52,this._ROUTER_CONFIGURATION_45)]); }
    return this.__APP_BOOTSTRAP_LISTENER_54;
  }
  get _LocalStorage_55():import35.LocalStorage {
    if ((this.__LocalStorage_55 == (null as any))) { (this.__LocalStorage_55 = new import35.LocalStorage()); }
    return this.__LocalStorage_55;
  }
  get _TVMaze_56():import36.TVMaze {
    if ((this.__TVMaze_56 == (null as any))) { (this.__TVMaze_56 = new import36.TVMaze(this._Http_42)); }
    return this.__TVMaze_56;
  }
  createInternal():import1.AppModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ApplicationModule_1 = new import3.ApplicationModule();
    this._BrowserModule_2 = new import4.BrowserModule(this.parent.get(import4.BrowserModule,(null as any)));
    this._ROUTER_FORROOT_GUARD_3 = import5.provideForRootGuard(this.parent.get(import56.Router,(null as any)));
    this._RouterModule_4 = new import5.RouterModule(this._ROUTER_FORROOT_GUARD_3);
    this._InternalFormsSharedModule_5 = new import6.InternalFormsSharedModule();
    this._ReactiveFormsModule_6 = new import7.ReactiveFormsModule();
    this._HttpModule_7 = new import8.HttpModule();
    this._ConfirmModule_8 = new import9.ConfirmModule();
    this._CalendarModule_9 = new import10.CalendarModule();
    this._AppModule_10 = new import1.AppModule();
    this._ErrorHandler_13 = import4.errorHandler();
    this._ApplicationInitStatus_14 = new import12.ApplicationInitStatus(this.parent.get(import12.APP_INITIALIZER,(null as any)));
    this._Testability_15 = new import13.Testability(this.parent.get(import48.NgZone));
    this._ApplicationRef__16 = new import14.ApplicationRef_(this.parent.get(import48.NgZone),this.parent.get(import57.Console),this,this._ErrorHandler_13,this,this._ApplicationInitStatus_14,this.parent.get(import13.TestabilityRegistry,(null as any)),this._Testability_15);
    return this._AppModule_10;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ApplicationModule)) { return this._ApplicationModule_1; }
    if ((token === import4.BrowserModule)) { return this._BrowserModule_2; }
    if ((token === import5.ROUTER_FORROOT_GUARD)) { return this._ROUTER_FORROOT_GUARD_3; }
    if ((token === import5.RouterModule)) { return this._RouterModule_4; }
    if ((token === import6.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_5; }
    if ((token === import7.ReactiveFormsModule)) { return this._ReactiveFormsModule_6; }
    if ((token === import8.HttpModule)) { return this._HttpModule_7; }
    if ((token === import9.ConfirmModule)) { return this._ConfirmModule_8; }
    if ((token === import10.CalendarModule)) { return this._CalendarModule_9; }
    if ((token === import1.AppModule)) { return this._AppModule_10; }
    if ((token === import58.LOCALE_ID)) { return this._LOCALE_ID_11; }
    if ((token === import11.NgLocalization)) { return this._NgLocalization_12; }
    if ((token === import59.ErrorHandler)) { return this._ErrorHandler_13; }
    if ((token === import12.ApplicationInitStatus)) { return this._ApplicationInitStatus_14; }
    if ((token === import13.Testability)) { return this._Testability_15; }
    if ((token === import14.ApplicationRef_)) { return this._ApplicationRef__16; }
    if ((token === import14.ApplicationRef)) { return this._ApplicationRef_17; }
    if ((token === import15.Compiler)) { return this._Compiler_18; }
    if ((token === import45.APP_ID)) { return this._APP_ID_19; }
    if ((token === import60.DOCUMENT)) { return this._DOCUMENT_20; }
    if ((token === import16.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_21; }
    if ((token === import17.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_22; }
    if ((token === import17.EventManager)) { return this._EventManager_23; }
    if ((token === import18.DomSharedStylesHost)) { return this._DomSharedStylesHost_24; }
    if ((token === import61.AnimationDriver)) { return this._AnimationDriver_25; }
    if ((token === import19.DomRootRenderer)) { return this._DomRootRenderer_26; }
    if ((token === import62.RootRenderer)) { return this._RootRenderer_27; }
    if ((token === import20.DomSanitizer)) { return this._DomSanitizer_28; }
    if ((token === import63.Sanitizer)) { return this._Sanitizer_29; }
    if ((token === import21.ViewUtils)) { return this._ViewUtils_30; }
    if ((token === import64.IterableDiffers)) { return this._IterableDiffers_31; }
    if ((token === import65.KeyValueDiffers)) { return this._KeyValueDiffers_32; }
    if ((token === import18.SharedStylesHost)) { return this._SharedStylesHost_33; }
    if ((token === import22.Title)) { return this._Title_34; }
    if ((token === import23.FormBuilder)) { return this._FormBuilder_35; }
    if ((token === import24.RadioControlRegistry)) { return this._RadioControlRegistry_36; }
    if ((token === import25.BrowserXhr)) { return this._BrowserXhr_37; }
    if ((token === import26.ResponseOptions)) { return this._ResponseOptions_38; }
    if ((token === import66.XSRFStrategy)) { return this._XSRFStrategy_39; }
    if ((token === import27.XHRBackend)) { return this._XHRBackend_40; }
    if ((token === import28.RequestOptions)) { return this._RequestOptions_41; }
    if ((token === import67.Http)) { return this._Http_42; }
    if ((token === import29.CalendarEventTitle)) { return this._CalendarEventTitle_43; }
    if ((token === import30.CalendarDateFormatter)) { return this._CalendarDateFormatter_44; }
    if ((token === import5.ROUTER_CONFIGURATION)) { return this._ROUTER_CONFIGURATION_45; }
    if ((token === import51.LocationStrategy)) { return this._LocationStrategy_46; }
    if ((token === import31.Location)) { return this._Location_47; }
    if ((token === import32.UrlSerializer)) { return this._UrlSerializer_48; }
    if ((token === import33.RouterOutletMap)) { return this._RouterOutletMap_49; }
    if ((token === import68.NgModuleFactoryLoader)) { return this._NgModuleFactoryLoader_50; }
    if ((token === import69.ROUTES)) { return this._ROUTES_51; }
    if ((token === import56.Router)) { return this._Router_52; }
    if ((token === import70.ActivatedRoute)) { return this._ActivatedRoute_53; }
    if ((token === import45.APP_BOOTSTRAP_LISTENER)) { return this._APP_BOOTSTRAP_LISTENER_54; }
    if ((token === import35.LocalStorage)) { return this._LocalStorage_55; }
    if ((token === import36.TVMaze)) { return this._TVMaze_56; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__16.ngOnDestroy();
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory(AppModuleInjector,import1.AppModule);